// Generated by Haxe 4.1.1

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.format {
	public class JsonPrinter : global::haxe.lang.HxObject {
		
		public JsonPrinter(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public JsonPrinter(global::haxe.lang.Function replacer, string space) {
			#line 56 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
			global::haxe.format.JsonPrinter.__hx_ctor_haxe_format_JsonPrinter(this, replacer, space);
		}
		#line default
		
		protected static void __hx_ctor_haxe_format_JsonPrinter(global::haxe.format.JsonPrinter __hx_this, global::haxe.lang.Function replacer, string space) {
			#line 57 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
			__hx_this.replacer = replacer;
			__hx_this.indent = space;
			#line 59 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
			__hx_this.pretty = ( space != null );
			__hx_this.nind = 0;
			#line 67 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
			__hx_this.buf = new global::StringBuf();
		}
		#line default
		
		public static string print(object o, global::haxe.lang.Function replacer, string space) {
			#line 45 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
			global::haxe.format.JsonPrinter printer = new global::haxe.format.JsonPrinter(replacer, space);
			printer.write("", o);
			#line 47 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
			return printer.buf.b.ToString();
		}
		#line default
		
		public global::StringBuf buf;
		
		public global::haxe.lang.Function replacer;
		
		public string indent;
		
		public bool pretty;
		
		public int nind;
		
		public void ipad() {
			#line 72 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
			if (this.pretty) {
				#line 73 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
				string v = global::StringTools.lpad("", this.indent, ( this.nind * this.indent.Length ));
				#line 73 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
				this.buf.b.Append(((string) (global::Std.@string(v)) ));
			}
			
		}
		#line default
		
		public void newl() {
			unchecked {
				#line 77 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
				if (this.pretty) {
					#line 78 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
					this.buf.addChar(10);
				}
				
			}
			#line default
		}
		
		
		public virtual void write(object k, object v) {
			unchecked {
				#line 82 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
				if (( this.replacer != null )) {
					#line 83 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
					v = ((object) (this.replacer.__hx_invoke2_o(default(double), k, default(double), v)) );
				}
				
				#line 84 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
				{
					#line 84 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
					global::ValueType _g = global::Type.@typeof(v);
					#line 84 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
					switch (_g._hx_index) {
						case 0:
						{
							#line 136 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							this.buf.b.Append(((string) ("null") ));
							#line 136 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							break;
						}
						
						
						case 1:
						{
							#line 90 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							this.buf.b.Append(((string) (global::Std.@string(global::haxe.lang.Runtime.toString(v))) ));
							#line 90 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							break;
						}
						
						
						case 2:
						{
							#line 92 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							double f = ((double) (global::haxe.lang.Runtime.toDouble(v)) );
							#line 92 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							string v1 = ( ((  ! (global::System.Double.IsInfinity(((double) (f) )))  &&  ! (global::System.Double.IsNaN(((double) (f) )))  )) ? (global::Std.@string(v)) : ("null") );
							#line 92 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							this.buf.b.Append(((string) (global::Std.@string(v1)) ));
							#line 92 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							break;
						}
						
						
						case 3:
						{
							#line 134 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							this.buf.b.Append(((string) (global::Std.@string(global::haxe.lang.Runtime.toString(v))) ));
							#line 134 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							break;
						}
						
						
						case 4:
						{
							#line 88 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							this.fieldsString(v, global::Reflect.fields(v));
							#line 88 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							break;
						}
						
						
						case 5:
						{
							#line 94 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							this.buf.b.Append(((string) ("\"<fun>\"") ));
							#line 94 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							break;
						}
						
						
						case 6:
						{
							#line 95 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							global::System.Type c = ( _g as global::ValueType_TClass ).c;
							if (global::haxe.lang.Runtime.refEq(c, typeof(string))) {
								#line 97 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
								this.quote(global::haxe.lang.Runtime.toString(v));
							}
							else if (global::haxe.lang.Runtime.refEq(c, typeof(global::Array<object>))) {
								#line 99 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
								global::Array v2 = ((global::Array) (v) );
								this.buf.addChar(91);
								#line 102 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
								int len = ((int) (global::haxe.lang.Runtime.getField_f(v2, "length", 520590566, true)) );
								int last = ( len - 1 );
								#line 104 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
								{
									#line 104 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
									int _g1 = 0;
									#line 104 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
									int _g2 = len;
									#line 104 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
									while (( _g1 < _g2 )) {
										#line 104 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
										int i = _g1++;
										if (( i > 0 )) {
											#line 106 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
											this.buf.addChar(44);
										}
										else {
											#line 108 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
											this.nind++;
										}
										
										#line 109 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
										if (this.pretty) {
											#line 109 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
											this.buf.addChar(10);
										}
										
										#line 110 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
										if (this.pretty) {
											#line 110 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
											string v3 = global::StringTools.lpad("", this.indent, ( this.nind * this.indent.Length ));
											#line 110 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
											this.buf.b.Append(((string) (global::Std.@string(v3)) ));
										}
										
										#line 111 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
										this.write(i, v2[i]);
										if (( i == last )) {
											#line 113 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
											this.nind--;
											if (this.pretty) {
												#line 114 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
												this.buf.addChar(10);
											}
											
											#line 115 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
											if (this.pretty) {
												#line 115 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
												string v4 = global::StringTools.lpad("", this.indent, ( this.nind * this.indent.Length ));
												#line 115 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
												this.buf.b.Append(((string) (global::Std.@string(v4)) ));
											}
											
										}
										
									}
									
								}
								
								#line 118 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
								this.buf.addChar(93);
							}
							else if (global::haxe.lang.Runtime.refEq(c, typeof(global::haxe.ds.StringMap<object>))) {
								#line 120 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
								global::haxe.ds.StringMap v5 = ((global::haxe.ds.StringMap) (v) );
								object o = new global::haxe.lang.DynamicObject(new int[]{}, new object[]{}, new int[]{}, new double[]{});
								#line 122 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
								{
									#line 122 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
									object k1 = ((object) (new global::haxe.ds._StringMap.StringMapKeyIterator<object>(((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (v5) ))) ))) );
									#line 122 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
									while (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(k1, "hasNext", 407283053, null))) {
										#line 122 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
										string k2 = global::haxe.lang.Runtime.toString(global::haxe.lang.Runtime.callField(k1, "next", 1224901875, null));
										global::Reflect.setField(o, k2, ((object) (global::haxe.lang.Runtime.callField(v5, "get", 5144726, new object[]{k2})) ));
									}
									
								}
								
								#line 124 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
								{
									#line 124 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
									object v6 = ((object) (o) );
									#line 124 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
									this.fieldsString(v6, global::Reflect.fields(v6));
								}
								
							}
							else if (global::haxe.lang.Runtime.refEq(c, typeof(global::Date))) {
								#line 126 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
								global::Date v7 = ((global::Date) (v) );
								this.quote(v7.toString());
							}
							else {
								#line 129 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
								this.classString(v);
							}
							
							#line 95 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							break;
						}
						
						
						case 7:
						{
							#line 130 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							global::System.Type _g3 = ( _g as global::ValueType_TEnum ).e;
							#line 130 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							{
								#line 131 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
								object i1 = global::Type.enumIndex(v);
								this.buf.b.Append(((string) (global::Std.@string(global::haxe.lang.Runtime.toString(i1))) ));
							}
							
							#line 130 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							break;
						}
						
						
						case 8:
						{
							#line 86 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							this.buf.b.Append(((string) ("\"???\"") ));
							#line 86 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							break;
						}
						
						
					}
					
				}
				
			}
			#line default
		}
		
		
		public virtual void classString(object v) {
			#line 158 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
			this.fieldsString(v, global::Type.getInstanceFields(global::Type.getClass<object>(((object) (v) ))));
		}
		#line default
		
		public void objString(object v) {
			#line 162 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
			this.fieldsString(v, global::Reflect.fields(v));
		}
		#line default
		
		public virtual void fieldsString(object v, global::Array<string> fields) {
			unchecked {
				#line 166 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
				this.buf.addChar(123);
				int len = fields.length;
				#line 168 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
				int last = ( len - 1 );
				bool first = true;
				#line 170 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
				{
					#line 170 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
					int _g = 0;
					#line 170 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
					int _g1 = len;
					#line 170 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
					while (( _g < _g1 )) {
						#line 170 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						int i = _g++;
						string f = fields[i];
						#line 172 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						object @value = global::Reflect.field(v, f);
						if (( ((object) (@value) ) is global::haxe.lang.Function )) {
							#line 174 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							continue;
						}
						
						#line 175 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						if (first) {
							#line 176 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							this.nind++;
							first = false;
						}
						else {
							#line 179 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							this.buf.addChar(44);
						}
						
						#line 180 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						if (this.pretty) {
							#line 180 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							this.buf.addChar(10);
						}
						
						#line 181 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						if (this.pretty) {
							#line 181 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							string v1 = global::StringTools.lpad("", this.indent, ( this.nind * this.indent.Length ));
							#line 181 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							this.buf.b.Append(((string) (global::Std.@string(v1)) ));
						}
						
						#line 182 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						this.quote(f);
						this.buf.addChar(58);
						#line 184 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						if (this.pretty) {
							#line 185 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							this.buf.addChar(32);
						}
						
						#line 186 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						this.write(f, @value);
						if (( i == last )) {
							#line 188 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							this.nind--;
							if (this.pretty) {
								#line 189 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
								this.buf.addChar(10);
							}
							
							#line 190 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							if (this.pretty) {
								#line 190 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
								string v2 = global::StringTools.lpad("", this.indent, ( this.nind * this.indent.Length ));
								#line 190 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
								this.buf.b.Append(((string) (global::Std.@string(v2)) ));
							}
							
						}
						
					}
					
				}
				
				#line 193 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
				this.buf.addChar(125);
			}
			#line default
		}
		
		
		public virtual void quote(string s) {
			unchecked {
				#line 203 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
				this.buf.addChar(34);
				int i = 0;
				#line 208 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
				while (true) {
					#line 209 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
					int index = i++;
					#line 209 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
					int c = ( (( ((uint) (index) ) < s.Length )) ? (((int) (s[index]) )) : (-1) );
					if (( c == -1 )) {
						#line 211 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						break;
					}
					
					#line 212 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
					switch (c) {
						case 8:
						{
							#line 224 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							this.buf.b.Append(((string) ("\\b") ));
							#line 224 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							break;
						}
						
						
						case 9:
						{
							#line 222 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							this.buf.b.Append(((string) ("\\t") ));
							#line 222 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							break;
						}
						
						
						case 10:
						{
							#line 218 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							this.buf.b.Append(((string) ("\\n") ));
							#line 218 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							break;
						}
						
						
						case 12:
						{
							#line 226 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							this.buf.b.Append(((string) ("\\f") ));
							#line 226 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							break;
						}
						
						
						case 13:
						{
							#line 220 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							this.buf.b.Append(((string) ("\\r") ));
							#line 220 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							break;
						}
						
						
						case 34:
						{
							#line 214 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							this.buf.b.Append(((string) ("\\\"") ));
							#line 214 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							break;
						}
						
						
						case 92:
						{
							#line 216 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							this.buf.b.Append(((string) ("\\\\") ));
							#line 216 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							break;
						}
						
						
						default:
						{
							#line 249 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							this.buf.addChar(c);
							#line 249 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
							break;
						}
						
					}
					
				}
				
				#line 257 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
				this.buf.addChar(34);
			}
			#line default
		}
		
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
				switch (hash) {
					case 1225098545:
					{
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						this.nind = ((int) (@value) );
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						return @value;
					}
					
					
					default:
					{
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
				switch (hash) {
					case 1225098545:
					{
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						this.nind = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						return @value;
					}
					
					
					case 784433846:
					{
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						this.pretty = global::haxe.lang.Runtime.toBool(@value);
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						return @value;
					}
					
					
					case 334695532:
					{
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						this.indent = global::haxe.lang.Runtime.toString(@value);
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						return @value;
					}
					
					
					case 404153790:
					{
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						this.replacer = ((global::haxe.lang.Function) (@value) );
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						return @value;
					}
					
					
					case 4899635:
					{
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						this.buf = ((global::StringBuf) (@value) );
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						return @value;
					}
					
					
					default:
					{
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
				switch (hash) {
					case 1576149820:
					{
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "quote", 1576149820)) );
					}
					
					
					case 878103594:
					{
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "fieldsString", 878103594)) );
					}
					
					
					case 1503920168:
					{
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "objString", 1503920168)) );
					}
					
					
					case 142151465:
					{
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "classString", 142151465)) );
					}
					
					
					case 1348037855:
					{
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "write", 1348037855)) );
					}
					
					
					case 1224901644:
					{
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "newl", 1224901644)) );
					}
					
					
					case 1169995914:
					{
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "ipad", 1169995914)) );
					}
					
					
					case 1225098545:
					{
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						return this.nind;
					}
					
					
					case 784433846:
					{
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						return this.pretty;
					}
					
					
					case 334695532:
					{
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						return this.indent;
					}
					
					
					case 404153790:
					{
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						return this.replacer;
					}
					
					
					case 4899635:
					{
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						return this.buf;
					}
					
					
					default:
					{
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
				switch (hash) {
					case 1225098545:
					{
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						return ((double) (this.nind) );
					}
					
					
					default:
					{
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
				switch (hash) {
					case 1576149820:
					{
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						this.quote(global::haxe.lang.Runtime.toString(dynargs[0]));
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						break;
					}
					
					
					case 878103594:
					{
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						this.fieldsString(dynargs[0], ((global::Array<string>) (global::Array<object>.__hx_cast<string>(((global::Array) (dynargs[1]) ))) ));
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						break;
					}
					
					
					case 1503920168:
					{
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						this.objString(dynargs[0]);
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						break;
					}
					
					
					case 142151465:
					{
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						this.classString(dynargs[0]);
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						break;
					}
					
					
					case 1348037855:
					{
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						this.write(dynargs[0], dynargs[1]);
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						break;
					}
					
					
					case 1224901644:
					{
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						this.newl();
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						break;
					}
					
					
					case 1169995914:
					{
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						this.ipad();
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						break;
					}
					
					
					default:
					{
						#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
				return null;
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
			baseArr.push("nind");
			#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
			baseArr.push("pretty");
			#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
			baseArr.push("indent");
			#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
			baseArr.push("replacer");
			#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
			baseArr.push("buf");
			#line 33 "/opt/haxe/std/haxe/format/JsonPrinter.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}


