// Generated by Haxe 4.1.1

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace cs {
	public class Boot : global::haxe.lang.HxObject {
		
		public Boot(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public Boot() {
			#line 41 "/opt/haxe/std/cs/Boot.hx"
			global::cs.Boot.__hx_ctor_cs_Boot(this);
		}
		#line default
		
		protected static void __hx_ctor_cs_Boot(global::cs.Boot __hx_this) {
		}
		
		
		public static void init() {
			#line 47 "/opt/haxe/std/cs/Boot.hx"
			global::cs.Lib.applyCultureChanges();
		}
		#line default
		
	}
}


