/nologo
/optimize+
/debug-
/unsafe-
/warn:0
/out:/builds/mindpowered/infra/maglev/build/vcs/csharp/bin/maglev.dll
/target:library
src\cs\NativeArray.cs
src\haxe\ds\List.cs
src\cs\Boot.cs
src\Std.cs
src\Xml.cs
src\haxe\lang\Null.cs
src\haxe\io\Output.cs
src\sys\Http.cs
src\haxe\http\HttpBase.cs
src\haxe\Log.cs
src\EnumValue.cs
src\haxe\crypto\Base64.cs
src\Array.cs
src\cs\internal\Function.cs
src\sys\net\Socket.cs
src\haxe\ds\BalancedTree.cs
src\haxe\format\JsonParser.cs
src\haxe\io\Encoding.cs
src\haxe\ds\ArraySort.cs
src\haxe\Int32.cs
src\Sys.cs
src\haxe\Exception.cs
src\haxe\io\Eof.cs
src\haxe\ds\ReadOnlyArray.cs
src\Type.cs
src\haxe\ds\Option.cs
src\haxe\ds\HashMap.cs
src\haxe\SysTools.cs
src\haxe\format\JsonPrinter.cs
src\Date.cs
src\maglev\Telemetry.cs
src\Lambda.cs
src\haxe\io\Error.cs
src\sys\io\FileSeek.cs
src\StringTools.cs
src\haxe\Int64.cs
src\haxe\iterators\ArrayIterator.cs
src\Reflect.cs
src\haxe\io\Bytes.cs
src\haxe\Json.cs
src\haxe\ds\Vector.cs
src\haxe\io\FPHelper.cs
src\haxe\Constraints.cs
src\sys\io\Process.cs
src\haxe\ds\ObjectMap.cs
src\haxe\crypto\BaseCode.cs
src\cs\Flags.cs
src\haxe\ds\GenericStack.cs
src\haxe\xml\Parser.cs
src\haxe\iterators\ArrayKeyValueIterator.cs
src\haxe\xml\Printer.cs
src\haxe\ds\StringMap.cs
src\haxe\ds\WeakMap.cs
src\maglev\MagLevCs.cs
src\sys\FileSystem.cs
src\haxe\ValueException.cs
src\haxe\iterators\StringIterator.cs
src\haxe\io\BytesOutput.cs
src\haxe\iterators\HashMapKeyValueIterator.cs
src\cs\internal\StringExt.cs
src\haxe\io\Path.cs
src\cs\internal\Runtime.cs
src\cs\Lib.cs
src\cs\io\NativeOutput.cs
src\haxe\ds\Either.cs
src\EReg.cs
src\haxe\iterators\StringIteratorUnicode.cs
src\haxe\ds\ListSort.cs
src\cs\internal\HxObject.cs
src\Math.cs
src\IntIterator.cs
src\haxe\iterators\StringKeyValueIterator.cs
src\cs\internal\FieldLookup.cs
src\haxe\ds\Map.cs
src\haxe\iterators\MapKeyValueIterator.cs
src\maglev\MagLev.cs
src\haxe\lang\DceNo.cs
src\haxe\io\BytesBuffer.cs
src\cs\io\NativeInput.cs
src\haxe\ds\EnumValueMap.cs
src\haxe\Int64Helper.cs
src\UInt.cs
src\haxe\io\BytesInput.cs
src\haxe\NativeStackTrace.cs
src\sys\net\Host.cs
src\haxe\ds\IntMap.cs
src\haxe\io\Input.cs
src\haxe\CallStack.cs
src\StringBuf.cs