// Generated by Haxe 4.1.1

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace maglev {
	public class MagLevCs : global::haxe.lang.HxObject {
		
		public MagLevCs(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public MagLevCs(global::maglev.MagLev maglev) {
			#line 22 "/my-component/src/maglev/MagLevCs.hx"
			global::maglev.MagLevCs.__hx_ctor_maglev_MagLevCs(this, maglev);
		}
		#line default
		
		protected static void __hx_ctor_maglev_MagLevCs(global::maglev.MagLevCs __hx_this, global::maglev.MagLev maglev) {
			#line 23 "/my-component/src/maglev/MagLevCs.hx"
			__hx_this.maglev = maglev;
		}
		#line default
		
		public static global::haxe.lang.Function listenerDelegateToHaxeFunction(global::System.Delegate @delegate) {
			#line 28 "/my-component/src/maglev/MagLevCs.hx"
			global::haxe.lang.Function func = new global::maglev.MagLevCs_listenerDelegateToHaxeFunction_28__Fun(@delegate);
			#line 34 "/my-component/src/maglev/MagLevCs.hx"
			return func;
		}
		#line default
		
		public static global::haxe.lang.Function callbackDelegateToHaxeFunction(global::System.Delegate @delegate) {
			#line 39 "/my-component/src/maglev/MagLevCs.hx"
			global::haxe.lang.Function func = new global::maglev.MagLevCs_callbackDelegateToHaxeFunction_39__Fun(@delegate);
			#line 44 "/my-component/src/maglev/MagLevCs.hx"
			return func;
		}
		#line default
		
		public static global::maglev.MagLevCs getInstance(string key) {
			#line 48 "/my-component/src/maglev/MagLevCs.hx"
			global::maglev.MagLevCs instance = new global::maglev.MagLevCs(((global::maglev.MagLev) (global::maglev.MagLev.getInstance(key)) ));
			return instance;
		}
		#line default
		
		public global::maglev.MagLev maglev;
		
		public virtual void register(string method, global::haxe.lang.Function callback) {
			#line 52 "/my-component/src/maglev/MagLevCs.hx"
			global::maglev.MagLevCs _gthis = this;
			global::haxe.lang.Function myfunc = new global::maglev.MagLevCs_register_53__Fun(callback, _gthis);
			#line 63 "/my-component/src/maglev/MagLevCs.hx"
			global::maglev.MagLevFunction mycallback = new global::maglev.MagLevFunction(myfunc, null);
			this.maglev.register(method, mycallback);
		}
		#line default
		
		public virtual void call(string method, global::Array<object> args, global::haxe.lang.Function callback) {
			#line 67 "/my-component/src/maglev/MagLevCs.hx"
			global::maglev.MagLevCs _gthis = this;
			global::maglev.MagLevArray myargs = new global::maglev.MagLevArray();
			#line 69 "/my-component/src/maglev/MagLevCs.hx"
			{
				#line 69 "/my-component/src/maglev/MagLevCs.hx"
				int _g = 0;
				#line 69 "/my-component/src/maglev/MagLevCs.hx"
				while (( _g < args.length )) {
					#line 69 "/my-component/src/maglev/MagLevCs.hx"
					object arg = args[_g];
					#line 69 "/my-component/src/maglev/MagLevCs.hx"
					 ++ _g;
					myargs.push(this.convertToMagLev(arg));
				}
				
			}
			
			#line 72 "/my-component/src/maglev/MagLevCs.hx"
			global::maglev.MagLevResult myresult = this.maglev.call(method, myargs);
			myresult.onError(( (( global::maglev.MagLevCs_call_73__Fun.__hx_current != null )) ? (global::maglev.MagLevCs_call_73__Fun.__hx_current) : (global::maglev.MagLevCs_call_73__Fun.__hx_current = ((global::maglev.MagLevCs_call_73__Fun) (new global::maglev.MagLevCs_call_73__Fun()) )) ));
			#line 76 "/my-component/src/maglev/MagLevCs.hx"
			myresult.onResult(new global::maglev.MagLevCs_call_76__Fun(callback, _gthis));
		}
		#line default
		
		public virtual void listen(string @event, global::haxe.lang.Function callback) {
			#line 82 "/my-component/src/maglev/MagLevCs.hx"
			global::maglev.MagLevCs _gthis = this;
			#line 84 "/my-component/src/maglev/MagLevCs.hx"
			global::haxe.lang.Function mysub = new global::maglev.MagLevCs_listen_84__Fun(@event, callback, _gthis);
			#line 94 "/my-component/src/maglev/MagLevCs.hx"
			global::maglev.MagLevFunction mycallback = new global::maglev.MagLevFunction(mysub, null);
			this.maglev.listen(@event, mycallback);
		}
		#line default
		
		public virtual void emit(string @event, global::Array<object> args) {
			#line 99 "/my-component/src/maglev/MagLevCs.hx"
			global::maglev.MagLevArray myargs = new global::maglev.MagLevArray();
			{
				#line 100 "/my-component/src/maglev/MagLevCs.hx"
				int _g = 0;
				#line 100 "/my-component/src/maglev/MagLevCs.hx"
				while (( _g < args.length )) {
					#line 100 "/my-component/src/maglev/MagLevCs.hx"
					object arg = args[_g];
					#line 100 "/my-component/src/maglev/MagLevCs.hx"
					 ++ _g;
					myargs.push(this.convertToMagLev(arg));
				}
				
			}
			
			#line 103 "/my-component/src/maglev/MagLevCs.hx"
			this.maglev.emit(@event, myargs);
		}
		#line default
		
		public virtual object convertToHaxe(global::maglev.MagLevAny x) {
			#line 107 "/my-component/src/maglev/MagLevCs.hx"
			if (( x.getType() == global::maglev.MagLevNull.getStaticType() )) {
				#line 108 "/my-component/src/maglev/MagLevCs.hx"
				return null;
			}
			else if (( x.getType() == global::maglev.MagLevBoolean.getStaticType() )) {
				#line 111 "/my-component/src/maglev/MagLevCs.hx"
				global::maglev.MagLevBoolean y = ((global::maglev.MagLevBoolean) (x) );
				return ((object) (y.getBool()) );
			}
			else if (( x.getType() == global::maglev.MagLevString.getStaticType() )) {
				#line 115 "/my-component/src/maglev/MagLevCs.hx"
				global::maglev.MagLevString y1 = ((global::maglev.MagLevString) (x) );
				return ((object) (y1.getString()) );
			}
			else if (( x.getType() == global::maglev.MagLevNumber.getStaticType() )) {
				#line 119 "/my-component/src/maglev/MagLevCs.hx"
				global::maglev.MagLevNumber y2 = ((global::maglev.MagLevNumber) (x) );
				return ((object) (y2.getFloat()) );
			}
			else if (( x.getType() == global::maglev.MagLevArray.getStaticType() )) {
				#line 123 "/my-component/src/maglev/MagLevCs.hx"
				global::maglev.MagLevArray y3 = ((global::maglev.MagLevArray) (x) );
				global::Array<object> arr = new global::Array<object>();
				#line 125 "/my-component/src/maglev/MagLevCs.hx"
				int i = 0;
				while (( i < y3.size() )) {
					#line 127 "/my-component/src/maglev/MagLevCs.hx"
					arr.push(this.convertToHaxe(y3.@get(i)));
					 ++ i;
				}
				
				#line 130 "/my-component/src/maglev/MagLevCs.hx"
				return ((object) (arr) );
			}
			else if (( x.getType() == global::maglev.MagLevObject.getStaticType() )) {
				#line 133 "/my-component/src/maglev/MagLevCs.hx"
				global::maglev.MagLevObject y4 = ((global::maglev.MagLevObject) (x) );
				global::haxe.ds.StringMap<object> map = new global::haxe.ds.StringMap<object>();
				#line 135 "/my-component/src/maglev/MagLevCs.hx"
				global::maglev.MagLevArray keys = y4.keys();
				int i1 = 0;
				#line 137 "/my-component/src/maglev/MagLevCs.hx"
				while (( i1 < keys.size() )) {
					#line 138 "/my-component/src/maglev/MagLevCs.hx"
					string key = (((global::maglev.MagLevString) (keys.@get(i1)) )).getString();
					map.@set(key, this.convertToHaxe(y4.@get(key)));
					#line 140 "/my-component/src/maglev/MagLevCs.hx"
					 ++ i1;
				}
				
				#line 142 "/my-component/src/maglev/MagLevCs.hx"
				return ((object) (map) );
			}
			else {
				#line 145 "/my-component/src/maglev/MagLevCs.hx"
				throw ((global::System.Exception) (global::haxe.Exception.thrown("convertToHaxe: unknown type")) );
			}
			
		}
		#line default
		
		public virtual global::maglev.MagLevAny convertToMagLev(object x) {
			#line 149 "/my-component/src/maglev/MagLevCs.hx"
			global::maglev.MagLevCs _gthis = this;
			if (( x == null )) {
				#line 151 "/my-component/src/maglev/MagLevCs.hx"
				return global::maglev.MagLevNull.create();
			}
			else if (global::Std.isOfType(((object) (x) ), ((object) (typeof(bool)) ))) {
				#line 154 "/my-component/src/maglev/MagLevCs.hx"
				return global::maglev.MagLevBoolean.fromBool(global::haxe.lang.Runtime.toBool(x));
			}
			else if (global::Std.isOfType(((object) (x) ), ((object) (typeof(string)) ))) {
				#line 157 "/my-component/src/maglev/MagLevCs.hx"
				return global::maglev.MagLevString.fromString(global::haxe.lang.Runtime.toString(x));
			}
			else if (global::Std.isOfType(((object) (x) ), ((object) (typeof(int)) ))) {
				#line 160 "/my-component/src/maglev/MagLevCs.hx"
				return global::maglev.MagLevNumber.fromInt(((int) (global::haxe.lang.Runtime.toInt(x)) ));
			}
			else if (global::Std.isOfType(((object) (x) ), ((object) (typeof(double)) ))) {
				#line 163 "/my-component/src/maglev/MagLevCs.hx"
				return global::maglev.MagLevNumber.fromFloat(((double) (global::haxe.lang.Runtime.toDouble(((object) (x) ))) ));
			}
			else if (( ((object) (x) ) is global::haxe.lang.Function )) {
				#line 166 "/my-component/src/maglev/MagLevCs.hx"
				global::haxe.lang.Function f = new global::maglev.MagLevCs_convertToMagLev_166__Fun(x, _gthis);
				#line 172 "/my-component/src/maglev/MagLevCs.hx"
				return global::maglev.MagLevFunction.fromFunction(f);
			}
			else if (global::Std.isOfType(((object) (x) ), ((object) (typeof(global::Array<object>)) ))) {
				#line 175 "/my-component/src/maglev/MagLevCs.hx"
				global::maglev.MagLevArray arr = global::maglev.MagLevArray.create();
				global::Array<object> y = ((global::Array<object>) (global::Array<object>.__hx_cast<object>(((global::Array) (((object) (x) )) ))) );
				#line 177 "/my-component/src/maglev/MagLevCs.hx"
				{
					#line 177 "/my-component/src/maglev/MagLevCs.hx"
					int _g = 0;
					#line 177 "/my-component/src/maglev/MagLevCs.hx"
					while (( _g < y.length )) {
						#line 177 "/my-component/src/maglev/MagLevCs.hx"
						object item = y[_g];
						#line 177 "/my-component/src/maglev/MagLevCs.hx"
						 ++ _g;
						arr.push(this.convertToMagLev(item));
					}
					
				}
				
				#line 180 "/my-component/src/maglev/MagLevCs.hx"
				return arr;
			}
			else if (global::Std.isOfType(((object) (x) ), ((object) (typeof(global::haxe.ds.StringMap<object>)) ))) {
				#line 183 "/my-component/src/maglev/MagLevCs.hx"
				global::haxe.ds.StringMap<object> map = ((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((object) (x) )) ))) );
				global::maglev.MagLevObject obj = global::maglev.MagLevObject.create();
				#line 185 "/my-component/src/maglev/MagLevCs.hx"
				{
					#line 185 "/my-component/src/maglev/MagLevCs.hx"
					object key = ((object) (new global::haxe.ds._StringMap.StringMapKeyIterator<object>(((global::haxe.ds.StringMap<object>) (map) ))) );
					#line 185 "/my-component/src/maglev/MagLevCs.hx"
					while (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(key, "hasNext", 407283053, null))) {
						#line 185 "/my-component/src/maglev/MagLevCs.hx"
						string key1 = global::haxe.lang.Runtime.toString(global::haxe.lang.Runtime.callField(key, "next", 1224901875, null));
						obj.@set(key1, this.convertToMagLev((map.@get(key1)).toDynamic()));
					}
					
				}
				
				#line 188 "/my-component/src/maglev/MagLevCs.hx"
				return obj;
			}
			else if (global::Reflect.isObject(x)) {
				#line 191 "/my-component/src/maglev/MagLevCs.hx"
				global::maglev.MagLevObject obj1 = global::maglev.MagLevObject.create();
				{
					#line 192 "/my-component/src/maglev/MagLevCs.hx"
					int _g1 = 0;
					#line 192 "/my-component/src/maglev/MagLevCs.hx"
					global::Array<string> _g2 = global::Reflect.fields(x);
					#line 192 "/my-component/src/maglev/MagLevCs.hx"
					while (( _g1 < _g2.length )) {
						#line 192 "/my-component/src/maglev/MagLevCs.hx"
						string field = _g2[_g1];
						#line 192 "/my-component/src/maglev/MagLevCs.hx"
						 ++ _g1;
						object val = global::Reflect.getProperty(x, field);
						#line 194 "/my-component/src/maglev/MagLevCs.hx"
						obj1.@set(field, this.convertToMagLev(val));
					}
					
				}
				
				#line 196 "/my-component/src/maglev/MagLevCs.hx"
				return obj1;
			}
			else {
				#line 199 "/my-component/src/maglev/MagLevCs.hx"
				throw ((global::System.Exception) (global::haxe.Exception.thrown("convertToMagLev: unknown type")) );
			}
			
		}
		#line default
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 18 "/my-component/src/maglev/MagLevCs.hx"
				switch (hash) {
					case 858513194:
					{
						#line 18 "/my-component/src/maglev/MagLevCs.hx"
						this.maglev = ((global::maglev.MagLev) (@value) );
						#line 18 "/my-component/src/maglev/MagLevCs.hx"
						return @value;
					}
					
					
					default:
					{
						#line 18 "/my-component/src/maglev/MagLevCs.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 18 "/my-component/src/maglev/MagLevCs.hx"
				switch (hash) {
					case 263824376:
					{
						#line 18 "/my-component/src/maglev/MagLevCs.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "convertToMagLev", 263824376)) );
					}
					
					
					case 907774356:
					{
						#line 18 "/my-component/src/maglev/MagLevCs.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "convertToHaxe", 907774356)) );
					}
					
					
					case 1125490259:
					{
						#line 18 "/my-component/src/maglev/MagLevCs.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "emit", 1125490259)) );
					}
					
					
					case 1878640711:
					{
						#line 18 "/my-component/src/maglev/MagLevCs.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "listen", 1878640711)) );
					}
					
					
					case 1102715038:
					{
						#line 18 "/my-component/src/maglev/MagLevCs.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "call", 1102715038)) );
					}
					
					
					case 1352640099:
					{
						#line 18 "/my-component/src/maglev/MagLevCs.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "register", 1352640099)) );
					}
					
					
					case 858513194:
					{
						#line 18 "/my-component/src/maglev/MagLevCs.hx"
						return this.maglev;
					}
					
					
					default:
					{
						#line 18 "/my-component/src/maglev/MagLevCs.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				#line 18 "/my-component/src/maglev/MagLevCs.hx"
				switch (hash) {
					case 263824376:
					{
						#line 18 "/my-component/src/maglev/MagLevCs.hx"
						return this.convertToMagLev(dynargs[0]);
					}
					
					
					case 907774356:
					{
						#line 18 "/my-component/src/maglev/MagLevCs.hx"
						return this.convertToHaxe(((global::maglev.MagLevAny) (dynargs[0]) ));
					}
					
					
					case 1125490259:
					{
						#line 18 "/my-component/src/maglev/MagLevCs.hx"
						this.emit(global::haxe.lang.Runtime.toString(dynargs[0]), ((global::Array<object>) (global::Array<object>.__hx_cast<object>(((global::Array) (dynargs[1]) ))) ));
						#line 18 "/my-component/src/maglev/MagLevCs.hx"
						break;
					}
					
					
					case 1878640711:
					{
						#line 18 "/my-component/src/maglev/MagLevCs.hx"
						this.listen(global::haxe.lang.Runtime.toString(dynargs[0]), ((global::haxe.lang.Function) (dynargs[1]) ));
						#line 18 "/my-component/src/maglev/MagLevCs.hx"
						break;
					}
					
					
					case 1102715038:
					{
						#line 18 "/my-component/src/maglev/MagLevCs.hx"
						this.call(global::haxe.lang.Runtime.toString(dynargs[0]), ((global::Array<object>) (global::Array<object>.__hx_cast<object>(((global::Array) (dynargs[1]) ))) ), ((global::haxe.lang.Function) (dynargs[2]) ));
						#line 18 "/my-component/src/maglev/MagLevCs.hx"
						break;
					}
					
					
					case 1352640099:
					{
						#line 18 "/my-component/src/maglev/MagLevCs.hx"
						this.register(global::haxe.lang.Runtime.toString(dynargs[0]), ((global::haxe.lang.Function) (dynargs[1]) ));
						#line 18 "/my-component/src/maglev/MagLevCs.hx"
						break;
					}
					
					
					default:
					{
						#line 18 "/my-component/src/maglev/MagLevCs.hx"
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				#line 18 "/my-component/src/maglev/MagLevCs.hx"
				return null;
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 18 "/my-component/src/maglev/MagLevCs.hx"
			baseArr.push("maglev");
			#line 18 "/my-component/src/maglev/MagLevCs.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace maglev {
	public class MagLevCs_register_53__Fun : global::haxe.lang.Function {
		
		public MagLevCs_register_53__Fun(global::haxe.lang.Function callback, global::maglev.MagLevCs _gthis) : base(1, 0) {
			#line 53 "/my-component/src/maglev/MagLevCs.hx"
			this.callback = callback;
			#line 53 "/my-component/src/maglev/MagLevCs.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 53 "/my-component/src/maglev/MagLevCs.hx"
			global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
			global::Array<object> arr = new global::Array<object>();
			#line 55 "/my-component/src/maglev/MagLevCs.hx"
			int i = 0;
			while (( i < args.size() )) {
				#line 57 "/my-component/src/maglev/MagLevCs.hx"
				arr.push(this._gthis.convertToHaxe(args.@get(i)));
				 ++ i;
			}
			
			#line 60 "/my-component/src/maglev/MagLevCs.hx"
			global::maglev.MagLevAny result = this._gthis.convertToMagLev(((object) (this.callback.__hx_invoke1_o(default(double), arr)) ));
			return global::maglev.MagLevResult.fromResult(result);
		}
		#line default
		
		public global::haxe.lang.Function callback;
		
		public global::maglev.MagLevCs _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace maglev {
	public class MagLevCs_call_73__Fun : global::haxe.lang.Function {
		
		public MagLevCs_call_73__Fun() : base(1, 0) {
		}
		
		
		public static global::maglev.MagLevCs_call_73__Fun __hx_current;
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 73 "/my-component/src/maglev/MagLevCs.hx"
			global::maglev.MagLevError error = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevError) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevError) (__fn_dyn1) )) );
			throw ((global::System.Exception) (global::haxe.Exception.thrown(error.getMessage())) );
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace maglev {
	public class MagLevCs_call_76__Fun : global::haxe.lang.Function {
		
		public MagLevCs_call_76__Fun(global::haxe.lang.Function callback, global::maglev.MagLevCs _gthis) : base(1, 0) {
			#line 76 "/my-component/src/maglev/MagLevCs.hx"
			this.callback = callback;
			#line 76 "/my-component/src/maglev/MagLevCs.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 76 "/my-component/src/maglev/MagLevCs.hx"
			global::maglev.MagLevAny result = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevAny) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevAny) (__fn_dyn1) )) );
			this.callback.__hx_invoke1_o(default(double), this._gthis.convertToHaxe(result));
			#line 78 "/my-component/src/maglev/MagLevCs.hx"
			return global::maglev.MagLevResult.fromResult(global::maglev.MagLevNull.create());
		}
		#line default
		
		public global::haxe.lang.Function callback;
		
		public global::maglev.MagLevCs _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace maglev {
	public class MagLevCs_listen_84__Fun : global::haxe.lang.Function {
		
		public MagLevCs_listen_84__Fun(string @event, global::haxe.lang.Function callback, global::maglev.MagLevCs _gthis) : base(1, 0) {
			#line 84 "/my-component/src/maglev/MagLevCs.hx"
			this.@event = @event;
			#line 84 "/my-component/src/maglev/MagLevCs.hx"
			this.callback = callback;
			#line 84 "/my-component/src/maglev/MagLevCs.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 84 "/my-component/src/maglev/MagLevCs.hx"
			global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
			global::Array<object> arr = new global::Array<object>();
			#line 86 "/my-component/src/maglev/MagLevCs.hx"
			int i = 0;
			while (( i < args.size() )) {
				#line 88 "/my-component/src/maglev/MagLevCs.hx"
				arr.push(this._gthis.convertToHaxe(args.@get(i)));
				 ++ i;
			}
			
			#line 91 "/my-component/src/maglev/MagLevCs.hx"
			this.callback.__hx_invoke2_o(default(double), this.@event, default(double), arr);
			return null;
		}
		#line default
		
		public string @event;
		
		public global::haxe.lang.Function callback;
		
		public global::maglev.MagLevCs _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace maglev {
	public class MagLevCs_convertToMagLev_166__Fun : global::haxe.lang.Function {
		
		public MagLevCs_convertToMagLev_166__Fun(object x, global::maglev.MagLevCs _gthis) : base(1, 0) {
			#line 166 "/my-component/src/maglev/MagLevCs.hx"
			this.x = x;
			#line 166 "/my-component/src/maglev/MagLevCs.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 166 "/my-component/src/maglev/MagLevCs.hx"
			global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
			global::haxe.lang.Function y = ((global::haxe.lang.Function) (((object) (this.x) )) );
			#line 168 "/my-component/src/maglev/MagLevCs.hx"
			object haxeArgs = this._gthis.convertToHaxe(args);
			object haxeRet = ((object) (y.__hx_invoke1_o(default(double), haxeArgs)) );
			#line 170 "/my-component/src/maglev/MagLevCs.hx"
			return global::maglev.MagLevResult.fromResult(this._gthis.convertToMagLev(haxeRet));
		}
		#line default
		
		public object x;
		
		public global::maglev.MagLevCs _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace maglev {
	public class MagLevCs_listenerDelegateToHaxeFunction_28__Fun : global::haxe.lang.Function {
		
		public MagLevCs_listenerDelegateToHaxeFunction_28__Fun(global::System.Delegate @delegate) : base(2, 0) {
			#line 28 "/my-component/src/maglev/MagLevCs.hx"
			this.@delegate = @delegate;
		}
		#line default
		
		public override object __hx_invoke2_o(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			unchecked {
				#line 28 "/my-component/src/maglev/MagLevCs.hx"
				global::Array args = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((global::Array) (((object) (__fn_float2) )) )) : (((global::Array) (__fn_dyn2) )) );
				#line 28 "/my-component/src/maglev/MagLevCs.hx"
				string ev = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (global::haxe.lang.Runtime.toString(__fn_float1)) : (global::haxe.lang.Runtime.toString(__fn_dyn1)) );
				object[] arr = new object[2];
				#line 30 "/my-component/src/maglev/MagLevCs.hx"
				( arr as global::System.Array ).SetValue(((object) (ev) ), ((int) (0) ));
				( arr as global::System.Array ).SetValue(((object) (args) ), ((int) (1) ));
				#line 32 "/my-component/src/maglev/MagLevCs.hx"
				return this.@delegate.DynamicInvoke(((object[]) (arr) ));
			}
			#line default
		}
		
		
		public global::System.Delegate @delegate;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace maglev {
	public class MagLevCs_callbackDelegateToHaxeFunction_39__Fun : global::haxe.lang.Function {
		
		public MagLevCs_callbackDelegateToHaxeFunction_39__Fun(global::System.Delegate @delegate) : base(1, 0) {
			#line 39 "/my-component/src/maglev/MagLevCs.hx"
			this.@delegate = @delegate;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			unchecked {
				#line 39 "/my-component/src/maglev/MagLevCs.hx"
				object ret = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((object) (__fn_float1) )) : (((object) (__fn_dyn1) )) );
				object[] arr = new object[1];
				#line 41 "/my-component/src/maglev/MagLevCs.hx"
				( arr as global::System.Array ).SetValue(((object) (ret) ), ((int) (0) ));
				this.@delegate.DynamicInvoke(((object[]) (arr) ));
				#line 39 "/my-component/src/maglev/MagLevCs.hx"
				return null;
			}
			#line default
		}
		
		
		public global::System.Delegate @delegate;
		
	}
}


