// Generated by Haxe 4.1.1

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.ds {
	public class BalancedTree<K, V> : global::haxe.lang.HxObject, global::haxe.ds.BalancedTree, global::haxe.IMap<K, V> {
		
		public BalancedTree(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public BalancedTree() {
			#line 41 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			global::haxe.ds.BalancedTree<object, object>.__hx_ctor_haxe_ds_BalancedTree<K, V>(((global::haxe.ds.BalancedTree<K, V>) (this) ));
		}
		#line default
		
		protected static void __hx_ctor_haxe_ds_BalancedTree<K_c, V_c>(global::haxe.ds.BalancedTree<K_c, V_c> __hx_this) {
		}
		
		
		public static object __hx_cast<K_c_c, V_c_c>(global::haxe.ds.BalancedTree me) {
			#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			return ( (( me != null )) ? (me.haxe_ds_BalancedTree_cast<K_c_c, V_c_c>()) : default(object) );
		}
		#line default
		
		public static void iteratorLoop<K1, V2>(global::haxe.ds.TreeNode<K1, V2> node, global::Array<V2> acc) {
			#line 173 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			if (( node != null )) {
				#line 174 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				global::haxe.ds.BalancedTree<object, object>.iteratorLoop<K1, V2>(((global::haxe.ds.TreeNode<K1, V2>) (node.left) ), ((global::Array<V2>) (acc) ));
				acc.push(node.@value);
				#line 176 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				global::haxe.ds.BalancedTree<object, object>.iteratorLoop<K1, V2>(((global::haxe.ds.TreeNode<K1, V2>) (node.right) ), ((global::Array<V2>) (acc) ));
			}
			
		}
		#line default
		
		global::haxe.IMap<K, V> global::haxe.IMap<K, V>.copy() {
			#line 144 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			return ((global::haxe.IMap<K, V>) (this.copy()) );
		}
		#line default
		
		public virtual object haxe_ds_BalancedTree_cast<K_c, V_c>() {
			#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			if (( global::haxe.lang.Runtime.eq(typeof(K), typeof(K_c)) && global::haxe.lang.Runtime.eq(typeof(V), typeof(V_c)) )) {
				#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				return this;
			}
			
			#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			global::haxe.ds.BalancedTree<K_c, V_c> new_me = new global::haxe.ds.BalancedTree<K_c, V_c>(global::haxe.lang.EmptyObject.EMPTY);
			#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			global::Array<string> fields = global::Reflect.fields(this);
			#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			int i = 0;
			#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			while (( i < fields.length )) {
				#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				string field = fields[i++];
				#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				global::Reflect.setField(new_me, field, global::Reflect.field(this, field));
			}
			
			#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			return new_me;
		}
		#line default
		
		public virtual object haxe_IMap_cast<K_c, V_c>() {
			#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			return this.haxe_ds_BalancedTree_cast<K, V>();
		}
		#line default
		
		public global::haxe.ds.TreeNode<K, V> root;
		
		public virtual void @set(K key, V @value) {
			#line 51 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			this.root = this.setLoop(key, @value, this.root);
		}
		#line default
		
		public virtual global::haxe.lang.Null<V> @get(K key) {
			#line 62 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			global::haxe.ds.TreeNode<K, V> node = this.root;
			while (( node != null )) {
				#line 64 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				int c = this.compare(key, node.key);
				if (( c == 0 )) {
					#line 66 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
					return new global::haxe.lang.Null<V>(node.@value, true);
				}
				
				#line 67 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				if (( c < 0 )) {
					#line 68 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
					node = node.left;
				}
				else {
					#line 70 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
					node = node.right;
				}
				
			}
			
			#line 72 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			return default(global::haxe.lang.Null<V>);
		}
		#line default
		
		public virtual bool @remove(K key) {
			#line 86 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			try {
				#line 87 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				this.root = this.removeLoop(key, this.root);
				return true;
			}
			catch (global::System.Exception _g){
				{
					global::haxe.NativeStackTrace.exception = ((global::System.Exception) (((object) (_g) )) );
				}
				
				#line 86 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				if (( ((object) (global::haxe.Exception.caught(_g).unwrap()) ) is string )) {
					#line 90 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
					return false;
				}
				else {
					#line 86 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
					throw _g;
				}
				
			}
			
			
		}
		#line default
		
		public virtual bool exists(K key) {
			#line 102 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			global::haxe.ds.TreeNode<K, V> node = this.root;
			while (( node != null )) {
				#line 104 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				int c = this.compare(key, node.key);
				if (( c == 0 )) {
					#line 106 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
					return true;
				}
				else if (( c < 0 )) {
					#line 108 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
					node = node.left;
				}
				else {
					#line 110 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
					node = node.right;
				}
				
			}
			
			#line 112 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			return false;
		}
		#line default
		
		public virtual object iterator() {
			#line 121 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			global::Array<V> ret = new global::Array<V>(new V[]{});
			global::haxe.ds.BalancedTree<object, object>.iteratorLoop<K, V>(((global::haxe.ds.TreeNode<K, V>) (this.root) ), ((global::Array<V>) (ret) ));
			#line 123 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			return new global::haxe.iterators.ArrayIterator<V>(((global::Array<V>) (ret) ));
		}
		#line default
		
		public object keyValueIterator() {
			#line 130 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			return new global::haxe.iterators.MapKeyValueIterator<K, V>(((global::haxe.IMap<K, V>) (this) ));
		}
		#line default
		
		public virtual object keys() {
			#line 139 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			global::Array<K> ret = new global::Array<K>(new K[]{});
			this.keysLoop(this.root, ret);
			#line 141 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			return new global::haxe.iterators.ArrayIterator<K>(((global::Array<K>) (ret) ));
		}
		#line default
		
		public virtual global::haxe.ds.BalancedTree<K, V> copy() {
			#line 145 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			global::haxe.ds.BalancedTree<K, V> copied = new global::haxe.ds.BalancedTree<K, V>();
			copied.root = this.root;
			#line 147 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			return copied;
		}
		#line default
		
		public virtual global::haxe.ds.TreeNode<K, V> setLoop(K k, V v, global::haxe.ds.TreeNode<K, V> node) {
			#line 151 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			if (( node == null )) {
				#line 152 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				return new global::haxe.ds.TreeNode<K, V>(null, k, v, null, default(global::haxe.lang.Null<int>));
			}
			
			#line 153 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			int c = this.compare(k, node.key);
			if (( c == 0 )) {
				#line 154 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				return new global::haxe.ds.TreeNode<K, V>(node.left, k, v, node.right, new global::haxe.lang.Null<int>(( (( node == null )) ? (0) : (node._height) ), true));
			}
			else if (( c < 0 )) {
				#line 155 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				global::haxe.ds.TreeNode<K, V> nl = this.setLoop(k, v, node.left);
				return this.balance(nl, node.key, node.@value, node.right);
			}
			else {
				#line 158 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				global::haxe.ds.TreeNode<K, V> nr = this.setLoop(k, v, node.right);
				return this.balance(node.left, node.key, node.@value, nr);
			}
			
		}
		#line default
		
		public virtual global::haxe.ds.TreeNode<K, V> removeLoop(K k, global::haxe.ds.TreeNode<K, V> node) {
			#line 164 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			if (( node == null )) {
				#line 165 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				throw ((global::System.Exception) (global::haxe.Exception.thrown("Not_found")) );
			}
			
			#line 166 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			int c = this.compare(k, node.key);
			if (( c == 0 )) {
				#line 167 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				return this.merge(node.left, node.right);
			}
			else if (( c < 0 )) {
				#line 168 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				return this.balance(this.removeLoop(k, node.left), node.key, node.@value, node.right);
			}
			else {
				#line 169 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				return this.balance(node.left, node.key, node.@value, this.removeLoop(k, node.right));
			}
			
		}
		#line default
		
		public virtual void keysLoop(global::haxe.ds.TreeNode<K, V> node, global::Array<K> acc) {
			#line 181 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			if (( node != null )) {
				#line 182 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				this.keysLoop(node.left, acc);
				acc.push(node.key);
				#line 184 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				this.keysLoop(node.right, acc);
			}
			
		}
		#line default
		
		public virtual global::haxe.ds.TreeNode<K, V> merge(global::haxe.ds.TreeNode<K, V> t1, global::haxe.ds.TreeNode<K, V> t2) {
			#line 189 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			if (( t1 == null )) {
				#line 190 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				return t2;
			}
			
			#line 191 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			if (( t2 == null )) {
				#line 192 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				return t1;
			}
			
			#line 193 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			global::haxe.ds.TreeNode<K, V> t = this.minBinding(t2);
			return this.balance(t1, t.key, t.@value, this.removeMinBinding(t2));
		}
		#line default
		
		public virtual global::haxe.ds.TreeNode<K, V> minBinding(global::haxe.ds.TreeNode<K, V> t) {
			#line 198 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			if (( t == null )) {
				#line 198 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				throw ((global::System.Exception) (global::haxe.Exception.thrown("Not_found")) );
			}
			else if (( t.left == null )) {
				#line 198 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				return t;
			}
			else {
				#line 198 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				return this.minBinding(t.left);
			}
			
		}
		#line default
		
		public virtual global::haxe.ds.TreeNode<K, V> removeMinBinding(global::haxe.ds.TreeNode<K, V> t) {
			#line 202 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			if (( t.left == null )) {
				#line 202 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				return t.right;
			}
			else {
				#line 202 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				return this.balance(this.removeMinBinding(t.left), t.key, t.@value, t.right);
			}
			
		}
		#line default
		
		public virtual global::haxe.ds.TreeNode<K, V> balance(global::haxe.ds.TreeNode<K, V> l, K k, V v, global::haxe.ds.TreeNode<K, V> r) {
			unchecked {
				#line 206 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				int hl = ( (( l == null )) ? (0) : (l._height) );
				int hr = ( (( r == null )) ? (0) : (r._height) );
				#line 208 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				if (( hl > ( hr + 2 ) )) {
					#line 209 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
					global::haxe.ds.TreeNode<K, V> _this = l.left;
					#line 209 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
					global::haxe.ds.TreeNode<K, V> _this1 = l.right;
					#line 209 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
					if (( (( (( _this == null )) ? (0) : (_this._height) )) >= (( (( _this1 == null )) ? (0) : (_this1._height) )) )) {
						#line 210 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return new global::haxe.ds.TreeNode<K, V>(l.left, l.key, l.@value, new global::haxe.ds.TreeNode<K, V>(l.right, k, v, r, default(global::haxe.lang.Null<int>)), default(global::haxe.lang.Null<int>));
					}
					else {
						#line 212 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return new global::haxe.ds.TreeNode<K, V>(new global::haxe.ds.TreeNode<K, V>(l.left, l.key, l.@value, l.right.left, default(global::haxe.lang.Null<int>)), l.right.key, l.right.@value, new global::haxe.ds.TreeNode<K, V>(l.right.right, k, v, r, default(global::haxe.lang.Null<int>)), default(global::haxe.lang.Null<int>));
					}
					
				}
				else if (( hr > ( hl + 2 ) )) {
					#line 215 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
					global::haxe.ds.TreeNode<K, V> _this2 = r.right;
					#line 215 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
					global::haxe.ds.TreeNode<K, V> _this3 = r.left;
					#line 215 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
					if (( (( (( _this2 == null )) ? (0) : (_this2._height) )) > (( (( _this3 == null )) ? (0) : (_this3._height) )) )) {
						#line 216 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return new global::haxe.ds.TreeNode<K, V>(new global::haxe.ds.TreeNode<K, V>(l, k, v, r.left, default(global::haxe.lang.Null<int>)), r.key, r.@value, r.right, default(global::haxe.lang.Null<int>));
					}
					else {
						#line 218 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return new global::haxe.ds.TreeNode<K, V>(new global::haxe.ds.TreeNode<K, V>(l, k, v, r.left.left, default(global::haxe.lang.Null<int>)), r.left.key, r.left.@value, new global::haxe.ds.TreeNode<K, V>(r.left.right, r.key, r.@value, r.right, default(global::haxe.lang.Null<int>)), default(global::haxe.lang.Null<int>));
					}
					
				}
				else {
					#line 221 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
					return new global::haxe.ds.TreeNode<K, V>(l, k, v, r, new global::haxe.lang.Null<int>(( (( (( hl > hr )) ? (hl) : (hr) )) + 1 ), true));
				}
				
			}
			#line default
		}
		
		
		public virtual int compare(K k1, K k2) {
			#line 226 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			return global::Reflect.compare<K>(global::haxe.lang.Runtime.genericCast<K>(k1), global::haxe.lang.Runtime.genericCast<K>(k2));
		}
		#line default
		
		public virtual string toString() {
			#line 230 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			if (( this.root == null )) {
				#line 230 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				return "{}";
			}
			else {
				#line 230 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				return global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("{", this.root.toString()), "}");
			}
			
		}
		#line default
		
		public virtual void clear() {
			#line 237 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			this.root = null;
		}
		#line default
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				switch (hash) {
					case 1269755426:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						this.root = ((global::haxe.ds.TreeNode<K, V>) (global::haxe.ds.TreeNode<object, object>.__hx_cast<K, V>(((global::haxe.ds.TreeNode) (@value) ))) );
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return @value;
					}
					
					
					default:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				switch (hash) {
					case 1213952397:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "clear", 1213952397)) );
					}
					
					
					case 946786476:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "toString", 946786476)) );
					}
					
					
					case 57219237:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "compare", 57219237)) );
					}
					
					
					case 596483356:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "balance", 596483356)) );
					}
					
					
					case 2123232567:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "removeMinBinding", 2123232567)) );
					}
					
					
					case 1155848147:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "minBinding", 1155848147)) );
					}
					
					
					case 96903864:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "merge", 96903864)) );
					}
					
					
					case 451001976:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "keysLoop", 451001976)) );
					}
					
					
					case 1154932936:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "removeLoop", 1154932936)) );
					}
					
					
					case 222029606:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "setLoop", 222029606)) );
					}
					
					
					case 1103412149:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "copy", 1103412149)) );
					}
					
					
					case 1191633396:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "keys", 1191633396)) );
					}
					
					
					case 1257164128:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "keyValueIterator", 1257164128)) );
					}
					
					
					case 328878574:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "iterator", 328878574)) );
					}
					
					
					case 1071652316:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "exists", 1071652316)) );
					}
					
					
					case 76061764:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "remove", 76061764)) );
					}
					
					
					case 5144726:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get", 5144726)) );
					}
					
					
					case 5741474:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "set", 5741474)) );
					}
					
					
					case 1269755426:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return this.root;
					}
					
					
					default:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				switch (hash) {
					case 1213952397:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						this.clear();
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						break;
					}
					
					
					case 946786476:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return this.toString();
					}
					
					
					case 57219237:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return this.compare(global::haxe.lang.Runtime.genericCast<K>(dynargs[0]), global::haxe.lang.Runtime.genericCast<K>(dynargs[1]));
					}
					
					
					case 596483356:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return this.balance(((global::haxe.ds.TreeNode<K, V>) (global::haxe.ds.TreeNode<object, object>.__hx_cast<K, V>(((global::haxe.ds.TreeNode) (dynargs[0]) ))) ), global::haxe.lang.Runtime.genericCast<K>(dynargs[1]), global::haxe.lang.Runtime.genericCast<V>(dynargs[2]), ((global::haxe.ds.TreeNode<K, V>) (global::haxe.ds.TreeNode<object, object>.__hx_cast<K, V>(((global::haxe.ds.TreeNode) (dynargs[3]) ))) ));
					}
					
					
					case 2123232567:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return this.removeMinBinding(((global::haxe.ds.TreeNode<K, V>) (global::haxe.ds.TreeNode<object, object>.__hx_cast<K, V>(((global::haxe.ds.TreeNode) (dynargs[0]) ))) ));
					}
					
					
					case 1155848147:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return this.minBinding(((global::haxe.ds.TreeNode<K, V>) (global::haxe.ds.TreeNode<object, object>.__hx_cast<K, V>(((global::haxe.ds.TreeNode) (dynargs[0]) ))) ));
					}
					
					
					case 96903864:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return this.merge(((global::haxe.ds.TreeNode<K, V>) (global::haxe.ds.TreeNode<object, object>.__hx_cast<K, V>(((global::haxe.ds.TreeNode) (dynargs[0]) ))) ), ((global::haxe.ds.TreeNode<K, V>) (global::haxe.ds.TreeNode<object, object>.__hx_cast<K, V>(((global::haxe.ds.TreeNode) (dynargs[1]) ))) ));
					}
					
					
					case 451001976:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						this.keysLoop(((global::haxe.ds.TreeNode<K, V>) (global::haxe.ds.TreeNode<object, object>.__hx_cast<K, V>(((global::haxe.ds.TreeNode) (dynargs[0]) ))) ), ((global::Array<K>) (global::Array<object>.__hx_cast<K>(((global::Array) (dynargs[1]) ))) ));
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						break;
					}
					
					
					case 1154932936:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return this.removeLoop(global::haxe.lang.Runtime.genericCast<K>(dynargs[0]), ((global::haxe.ds.TreeNode<K, V>) (global::haxe.ds.TreeNode<object, object>.__hx_cast<K, V>(((global::haxe.ds.TreeNode) (dynargs[1]) ))) ));
					}
					
					
					case 222029606:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return this.setLoop(global::haxe.lang.Runtime.genericCast<K>(dynargs[0]), global::haxe.lang.Runtime.genericCast<V>(dynargs[1]), ((global::haxe.ds.TreeNode<K, V>) (global::haxe.ds.TreeNode<object, object>.__hx_cast<K, V>(((global::haxe.ds.TreeNode) (dynargs[2]) ))) ));
					}
					
					
					case 1103412149:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return this.copy();
					}
					
					
					case 1191633396:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return this.keys();
					}
					
					
					case 1257164128:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return this.keyValueIterator();
					}
					
					
					case 328878574:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return this.iterator();
					}
					
					
					case 1071652316:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return this.exists(global::haxe.lang.Runtime.genericCast<K>(dynargs[0]));
					}
					
					
					case 76061764:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return this.@remove(global::haxe.lang.Runtime.genericCast<K>(dynargs[0]));
					}
					
					
					case 5144726:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return (this.@get(global::haxe.lang.Runtime.genericCast<K>(dynargs[0]))).toDynamic();
					}
					
					
					case 5741474:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						this.@set(global::haxe.lang.Runtime.genericCast<K>(dynargs[0]), global::haxe.lang.Runtime.genericCast<V>(dynargs[1]));
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						break;
					}
					
					
					default:
					{
						#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				return null;
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			baseArr.push("root");
			#line 35 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
		public override string ToString(){
			return this.toString();
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.ds {
	[global::haxe.lang.GenericInterface(typeof(global::haxe.ds.BalancedTree<object, object>))]
	public interface BalancedTree : global::haxe.lang.IHxObject, global::haxe.lang.IGenericObject {
		
		object haxe_ds_BalancedTree_cast<K_c, V_c>();
		
		object haxe_IMap_cast<K_c, V_c>();
		
		object iterator();
		
		object keyValueIterator();
		
		object keys();
		
		string toString();
		
		void clear();
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.ds {
	public class TreeNode<K, V> : global::haxe.lang.HxObject, global::haxe.ds.TreeNode {
		
		public TreeNode(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public TreeNode(global::haxe.ds.TreeNode<K, V> l, K k, V v, global::haxe.ds.TreeNode<K, V> r, global::haxe.lang.Null<int> h) {
			#line 252 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			global::haxe.ds.TreeNode<object, object>.__hx_ctor_haxe_ds_TreeNode<K, V>(((global::haxe.ds.TreeNode<K, V>) (this) ), ((global::haxe.ds.TreeNode<K, V>) (l) ), global::haxe.lang.Runtime.genericCast<K>(k), global::haxe.lang.Runtime.genericCast<V>(v), ((global::haxe.ds.TreeNode<K, V>) (r) ), ((global::haxe.lang.Null<int>) (h) ));
		}
		#line default
		
		protected static void __hx_ctor_haxe_ds_TreeNode<K_c, V_c>(global::haxe.ds.TreeNode<K_c, V_c> __hx_this, global::haxe.ds.TreeNode<K_c, V_c> l, K_c k, V_c v, global::haxe.ds.TreeNode<K_c, V_c> r, global::haxe.lang.Null<int> h) {
			unchecked {
				#line 252 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				int h1 = ( ( ! (h.hasValue) ) ? (-1) : ((h).@value) );
				__hx_this.left = l;
				#line 254 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				__hx_this.key = k;
				__hx_this.@value = v;
				#line 256 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				__hx_this.right = r;
				if (( h1 == -1 )) {
					#line 258 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
					int tmp = default(int);
					#line 258 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
					global::haxe.ds.TreeNode<K_c, V_c> _this = __hx_this.left;
					#line 258 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
					global::haxe.ds.TreeNode<K_c, V_c> _this1 = __hx_this.right;
					#line 258 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
					if (( (( (( _this == null )) ? (0) : (_this._height) )) > (( (( _this1 == null )) ? (0) : (_this1._height) )) )) {
						#line 258 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						global::haxe.ds.TreeNode<K_c, V_c> _this2 = __hx_this.left;
						#line 258 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						tmp = ( (( _this2 == null )) ? (0) : (_this2._height) );
					}
					else {
						#line 258 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						global::haxe.ds.TreeNode<K_c, V_c> _this3 = __hx_this.right;
						#line 258 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						tmp = ( (( _this3 == null )) ? (0) : (_this3._height) );
					}
					
					#line 258 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
					__hx_this._height = ( tmp + 1 );
				}
				else {
					#line 260 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
					__hx_this._height = h1;
				}
				
			}
			#line default
		}
		
		
		public static object __hx_cast<K_c_c, V_c_c>(global::haxe.ds.TreeNode me) {
			#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			return ( (( me != null )) ? (me.haxe_ds_TreeNode_cast<K_c_c, V_c_c>()) : default(object) );
		}
		#line default
		
		public virtual object haxe_ds_TreeNode_cast<K_c, V_c>() {
			#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			if (( global::haxe.lang.Runtime.eq(typeof(K), typeof(K_c)) && global::haxe.lang.Runtime.eq(typeof(V), typeof(V_c)) )) {
				#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				return this;
			}
			
			#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			global::haxe.ds.TreeNode<K_c, V_c> new_me = new global::haxe.ds.TreeNode<K_c, V_c>(global::haxe.lang.EmptyObject.EMPTY);
			#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			global::Array<string> fields = global::Reflect.fields(this);
			#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			int i = 0;
			#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			while (( i < fields.length )) {
				#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				string field = fields[i++];
				#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				global::Reflect.setField(new_me, field, global::Reflect.field(this, field));
			}
			
			#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			return new_me;
		}
		#line default
		
		public global::haxe.ds.TreeNode<K, V> left;
		
		public global::haxe.ds.TreeNode<K, V> right;
		
		public K key;
		
		public V @value;
		
		public int _height;
		
		public virtual string toString() {
			#line 267 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			return global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat((( (( this.left == null )) ? ("") : (global::haxe.lang.Runtime.concat(this.left.toString(), ", ")) )), (global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("", global::Std.@string(this.key)), "="), global::Std.@string(this.@value)))), (( (( this.right == null )) ? ("") : (global::haxe.lang.Runtime.concat(", ", this.right.toString())) )));
		}
		#line default
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				switch (hash) {
					case 1891834246:
					{
						#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						this._height = ((int) (@value) );
						#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return @value;
					}
					
					
					case 834174833:
					{
						#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						this.@value = global::haxe.lang.Runtime.genericCast<V>(((object) (@value) ));
						#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return ((double) (global::haxe.lang.Runtime.toDouble(((object) (@value) ))) );
					}
					
					
					case 5343647:
					{
						#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						this.key = global::haxe.lang.Runtime.genericCast<K>(((object) (@value) ));
						#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return ((double) (global::haxe.lang.Runtime.toDouble(((object) (@value) ))) );
					}
					
					
					default:
					{
						#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				switch (hash) {
					case 1891834246:
					{
						#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						this._height = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return @value;
					}
					
					
					case 834174833:
					{
						#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						this.@value = global::haxe.lang.Runtime.genericCast<V>(@value);
						#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return @value;
					}
					
					
					case 5343647:
					{
						#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						this.key = global::haxe.lang.Runtime.genericCast<K>(@value);
						#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return @value;
					}
					
					
					case 1768164316:
					{
						#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						this.right = ((global::haxe.ds.TreeNode<K, V>) (global::haxe.ds.TreeNode<object, object>.__hx_cast<K, V>(((global::haxe.ds.TreeNode) (@value) ))) );
						#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return @value;
					}
					
					
					case 1202718727:
					{
						#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						this.left = ((global::haxe.ds.TreeNode<K, V>) (global::haxe.ds.TreeNode<object, object>.__hx_cast<K, V>(((global::haxe.ds.TreeNode) (@value) ))) );
						#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return @value;
					}
					
					
					default:
					{
						#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				switch (hash) {
					case 946786476:
					{
						#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "toString", 946786476)) );
					}
					
					
					case 1891834246:
					{
						#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return this._height;
					}
					
					
					case 834174833:
					{
						#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return this.@value;
					}
					
					
					case 5343647:
					{
						#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return this.key;
					}
					
					
					case 1768164316:
					{
						#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return this.right;
					}
					
					
					case 1202718727:
					{
						#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return this.left;
					}
					
					
					default:
					{
						#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				switch (hash) {
					case 1891834246:
					{
						#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return ((double) (this._height) );
					}
					
					
					case 834174833:
					{
						#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return ((double) (global::haxe.lang.Runtime.toDouble(((object) (this.@value) ))) );
					}
					
					
					case 5343647:
					{
						#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return ((double) (global::haxe.lang.Runtime.toDouble(((object) (this.key) ))) );
					}
					
					
					default:
					{
						#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
				switch (hash) {
					case 946786476:
					{
						#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return this.toString();
					}
					
					
					default:
					{
						#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			baseArr.push("_height");
			#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			baseArr.push("value");
			#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			baseArr.push("key");
			#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			baseArr.push("right");
			#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			baseArr.push("left");
			#line 244 "/opt/haxe/std/haxe/ds/BalancedTree.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
		public override string ToString(){
			return this.toString();
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.ds {
	[global::haxe.lang.GenericInterface(typeof(global::haxe.ds.TreeNode<object, object>))]
	public interface TreeNode : global::haxe.lang.IHxObject, global::haxe.lang.IGenericObject {
		
		object haxe_ds_TreeNode_cast<K_c, V_c>();
		
		string toString();
		
	}
}


