// Generated by Haxe 4.1.1

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.ds {
	public class IntMap<T> : global::haxe.lang.HxObject, global::haxe.ds.IntMap, global::haxe.IMap<int, T> {
		
		static bool __hx_init_called = false;
		static IntMap() {
			if(global::haxe.ds.IntMap<object>.__hx_init_called) return;
			global::haxe.ds.IntMap<object>.__hx_init_called = true;
			{
				#line 35 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				global::haxe.ds.IntMap<object>.HASH_UPPER = 0.7;
			}
			
		}
		#line default
		
		public IntMap(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public IntMap() {
			#line 51 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			global::haxe.ds.IntMap<object>.__hx_ctor_haxe_ds_IntMap<T>(((global::haxe.ds.IntMap<T>) (this) ));
		}
		#line default
		
		protected static void __hx_ctor_haxe_ds_IntMap<T_c>(global::haxe.ds.IntMap<T_c> __hx_this) {
			unchecked {
				#line 53 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				__hx_this.cachedIndex = -1;
			}
			#line default
		}
		
		
		public static object __hx_cast<T_c_c>(global::haxe.ds.IntMap me) {
			#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			return ( (( me != null )) ? (me.haxe_ds_IntMap_cast<T_c_c>()) : default(object) );
		}
		#line default
		
		public static double HASH_UPPER;
		
		public static void assert(bool x) {
		}
		
		
		public static int defaultK() {
			#line 402 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			return 0;
		}
		#line default
		
		public static void arrayCopy(global::System.Array sourceArray, int sourceIndex, global::System.Array destinationArray, int destinationIndex, int length) {
			#line 406 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			global::System.Array.Copy(((global::System.Array) (sourceArray) ), ((int) (sourceIndex) ), ((global::System.Array) (destinationArray) ), ((int) (destinationIndex) ), ((int) (length) ));
		}
		#line default
		
		public static int getInc(int k, int mask) {
			unchecked {
				#line 410 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				return ( (( ( ( k >> 3 ) ^ ( k << 3 ) ) | 1 )) & mask );
			}
			#line default
		}
		
		
		public static int hash(int i) {
			#line 414 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			return i;
		}
		#line default
		
		public static int getFlag(int[] flags, int i) {
			unchecked {
				#line 424 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				return ( ((int) (( ((uint) (flags[( i >> 4 )]) ) >> (( (( i & 15 )) << 1 )) )) ) & 3 );
			}
			#line default
		}
		
		
		public static bool isDel(int flag) {
			unchecked {
				#line 428 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				return ( (( flag & 1 )) != 0 );
			}
			#line default
		}
		
		
		public static bool isEmpty(int flag) {
			unchecked {
				#line 432 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				return ( (( flag & 2 )) != 0 );
			}
			#line default
		}
		
		
		public static bool isEither(int flag) {
			#line 436 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			return ( flag != 0 );
		}
		#line default
		
		public static void setIsDelFalse(int[] flags, int i) {
			unchecked {
				#line 440 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				flags[( i >> 4 )] &=  ~ ((( 1 << (( (( i & 15 )) << 1 )) ))) ;
			}
			#line default
		}
		
		
		public static void setIsEmptyFalse(int[] flags, int i) {
			unchecked {
				#line 444 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				flags[( i >> 4 )] &=  ~ ((( 2 << (( (( i & 15 )) << 1 )) ))) ;
			}
			#line default
		}
		
		
		public static void setIsBothFalse(int[] flags, int i) {
			unchecked {
				#line 448 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				flags[( i >> 4 )] &=  ~ ((( 3 << (( (( i & 15 )) << 1 )) ))) ;
			}
			#line default
		}
		
		
		public static void setIsDelTrue(int[] flags, int i) {
			unchecked {
				#line 452 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				flags[( i >> 4 )] |= ( 1 << (( (( i & 15 )) << 1 )) );
			}
			#line default
		}
		
		
		public static int roundUp(int x) {
			unchecked {
				#line 456 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				 -- x;
				x |= ((int) (( ((uint) (x) ) >> 1 )) );
				#line 458 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				x |= ((int) (( ((uint) (x) ) >> 2 )) );
				x |= ((int) (( ((uint) (x) ) >> 4 )) );
				#line 460 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				x |= ((int) (( ((uint) (x) ) >> 8 )) );
				x |= ((int) (( ((uint) (x) ) >> 16 )) );
				#line 462 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				return  ++ x;
			}
			#line default
		}
		
		
		public static int flagsSize(int m) {
			unchecked {
				#line 466 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				if (( m < 16 )) {
					#line 466 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					return 1;
				}
				else {
					#line 466 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					return ( m >> 4 );
				}
				
			}
			#line default
		}
		
		
		global::haxe.IMap<int, T> global::haxe.IMap<int, T>.copy() {
			#line 358 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			return ((global::haxe.IMap<int, T>) (this.copy()) );
		}
		#line default
		
		public virtual object haxe_ds_IntMap_cast<T_c>() {
			unchecked {
				#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				if (global::haxe.lang.Runtime.eq(typeof(T), typeof(T_c))) {
					#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					return this;
				}
				
				#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				global::haxe.ds.IntMap<T_c> new_me = new global::haxe.ds.IntMap<T_c>(global::haxe.lang.EmptyObject.EMPTY);
				#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				global::Array<string> fields = global::Reflect.fields(this);
				#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				int i = 0;
				#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				while (( i < fields.length )) {
					#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					string field = fields[i++];
					#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					switch (field) {
						case "vals":
						{
							#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
							if (( this.vals != null )) {
								#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
								T_c[] __temp_new_arr1 = new T_c[this.vals.Length];
								#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
								int __temp_i2 = -1;
								#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
								while ((  ++ __temp_i2 < this.vals.Length )) {
									#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
									object __temp_obj3 = ((object) (this.vals[__temp_i2]) );
									#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
									if (( __temp_obj3 != null )) {
										#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
										__temp_new_arr1[__temp_i2] = global::haxe.lang.Runtime.genericCast<T_c>(__temp_obj3);
									}
									
								}
								
								#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
								new_me.vals = __temp_new_arr1;
							}
							else {
								#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
								new_me.vals = null;
							}
							
							#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
							break;
						}
						
						
						default:
						{
							#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
							global::Reflect.setField(new_me, field, global::Reflect.field(this, field));
							#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
							break;
						}
						
					}
					
				}
				
				#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				return new_me;
			}
			#line default
		}
		
		
		public virtual object haxe_IMap_cast<K_c, V_c>() {
			#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			return this.haxe_ds_IntMap_cast<T>();
		}
		#line default
		
		public int[] flags;
		
		public int[] _keys;
		
		public T[] vals;
		
		public int nBuckets;
		
		public int size;
		
		public int nOccupied;
		
		public int upperBound;
		
		public int cachedKey;
		
		public int cachedIndex;
		
		public virtual void @set(int key, T @value) {
			unchecked {
				#line 58 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				int targetIndex = default(int);
				if (( this.nOccupied >= this.upperBound )) {
					#line 60 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					if (( this.nBuckets > ( this.size << 1 ) )) {
						#line 61 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						this.resize(( this.nBuckets - 1 ));
					}
					else {
						#line 63 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						this.resize(( this.nBuckets + 1 ));
					}
					
				}
				
				#line 67 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				int[] flags = this.flags;
				#line 67 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				int[] _keys = this._keys;
				{
					#line 69 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					int mask = ( this.nBuckets - 1 );
					#line 69 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					int hashedKey = key;
					#line 69 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					int curIndex = ( hashedKey & mask );
					#line 73 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					int delKey = -1;
					#line 73 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					int curFlag = 0;
					#line 75 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					if (( (( ( ((int) (( ((uint) (flags[( curIndex >> 4 )]) ) >> (( (( curIndex & 15 )) << 1 )) )) ) & 3 ) & 2 )) != 0 )) {
						#line 76 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						targetIndex = curIndex;
					}
					else {
						#line 78 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						int inc = ( (( ( ( hashedKey >> 3 ) ^ ( hashedKey << 3 ) ) | 1 )) & mask );
						#line 78 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						int last = curIndex;
						while (true) {
							#line 79 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
							bool tmp = default(bool);
							#line 79 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
							if (( _keys[curIndex] != key )) {
								#line 79 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
								curFlag = ( ((int) (( ((uint) (flags[( curIndex >> 4 )]) ) >> (( (( curIndex & 15 )) << 1 )) )) ) & 3 );
								#line 79 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
								tmp = ( (( curFlag & 2 )) != 0 );
							}
							else {
								#line 79 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
								tmp = true;
							}
							
							#line 79 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
							if (tmp) {
								#line 79 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
								break;
							}
							
							#line 80 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
							if (( ( delKey == -1 ) && ( (( curFlag & 1 )) != 0 ) )) {
								#line 81 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
								delKey = curIndex;
							}
							
							#line 83 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
							curIndex = ( ( curIndex + inc ) & mask );
						}
						
						#line 89 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						if (( ( delKey != -1 ) && ( (( ( ((int) (( ((uint) (flags[( curIndex >> 4 )]) ) >> (( (( curIndex & 15 )) << 1 )) )) ) & 3 ) & 2 )) != 0 ) )) {
							#line 90 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
							targetIndex = delKey;
						}
						else {
							#line 92 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
							targetIndex = curIndex;
						}
						
					}
					
				}
				
				#line 97 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				int flag = ( ((int) (( ((uint) (flags[( targetIndex >> 4 )]) ) >> (( (( targetIndex & 15 )) << 1 )) )) ) & 3 );
				if (( (( flag & 2 )) != 0 )) {
					#line 99 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					_keys[targetIndex] = key;
					this.vals[targetIndex] = @value;
					#line 101 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					flags[( targetIndex >> 4 )] &=  ~ ((( 3 << (( (( targetIndex & 15 )) << 1 )) ))) ;
					this.size++;
					#line 103 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					this.nOccupied++;
				}
				else if (( (( flag & 1 )) != 0 )) {
					#line 105 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					_keys[targetIndex] = key;
					this.vals[targetIndex] = @value;
					#line 107 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					flags[( targetIndex >> 4 )] &=  ~ ((( 3 << (( (( targetIndex & 15 )) << 1 )) ))) ;
					this.size++;
				}
				else {
					#line 113 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					this.vals[targetIndex] = @value;
				}
				
			}
			#line default
		}
		
		
		public int lookup(int key) {
			unchecked {
				#line 118 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				if (( this.nBuckets != 0 )) {
					#line 119 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					int[] flags = this.flags;
					#line 119 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					int[] _keys = this._keys;
					#line 121 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					int mask = ( this.nBuckets - 1 );
					#line 121 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					int k = key;
					#line 121 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					int index = ( k & mask );
					#line 121 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					int curFlag = -1;
					#line 121 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					int inc = ( (( ( ( k >> 3 ) ^ ( k << 3 ) ) | 1 )) & mask );
					#line 121 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					int last = index;
					#line 127 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					while (true) {
						#line 128 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						if (( _keys[index] == key )) {
							#line 129 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
							curFlag = ( ((int) (( ((uint) (flags[( index >> 4 )]) ) >> (( (( index & 15 )) << 1 )) )) ) & 3 );
							#line 129 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
							if (( (( curFlag & 2 )) != 0 )) {
								#line 130 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
								index = ( ( index + inc ) & mask );
								#line 127 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
								if ( ! ((( index != last ))) ) {
									#line 127 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
									break;
								}
								else {
									#line 131 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
									continue;
								}
								
							}
							else if (( (( curFlag & 1 )) != 0 )) {
								#line 133 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
								return -1;
							}
							else {
								#line 135 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
								return index;
							}
							
						}
						else {
							#line 138 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
							index = ( ( index + inc ) & mask );
						}
						
						#line 127 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						if ( ! ((( index != last ))) ) {
							#line 127 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
							break;
						}
						
					}
					
				}
				
				#line 143 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				return -1;
			}
			#line default
		}
		
		
		public virtual global::haxe.lang.Null<T> @get(int key) {
			unchecked {
				#line 147 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				int idx = -1;
				#line 149 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				bool tmp = default(bool);
				#line 149 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				if (( this.cachedKey == key )) {
					#line 149 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					idx = this.cachedIndex;
					#line 149 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					tmp = ( idx != -1 );
				}
				else {
					#line 149 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					tmp = false;
				}
				
				#line 149 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				if (tmp) {
					#line 150 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					return new global::haxe.lang.Null<T>(global::haxe.lang.Runtime.genericCast<T>(this.vals[idx]), true);
				}
				
				#line 154 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				idx = this.lookup(key);
				if (( idx != -1 )) {
					#line 157 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					this.cachedKey = key;
					this.cachedIndex = idx;
					#line 160 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					return new global::haxe.lang.Null<T>(global::haxe.lang.Runtime.genericCast<T>(this.vals[idx]), true);
				}
				
				#line 163 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				return default(global::haxe.lang.Null<T>);
			}
			#line default
		}
		
		
		public virtual T getDefault(int key, T def) {
			unchecked {
				#line 167 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				int idx = -1;
				#line 169 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				bool tmp = default(bool);
				#line 169 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				if (( this.cachedKey == key )) {
					#line 169 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					idx = this.cachedIndex;
					#line 169 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					tmp = ( idx != -1 );
				}
				else {
					#line 169 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					tmp = false;
				}
				
				#line 169 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				if (tmp) {
					#line 170 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					return global::haxe.lang.Runtime.genericCast<T>(this.vals[idx]);
				}
				
				#line 174 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				idx = this.lookup(key);
				if (( idx != -1 )) {
					#line 177 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					this.cachedKey = key;
					this.cachedIndex = idx;
					#line 180 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					return global::haxe.lang.Runtime.genericCast<T>(this.vals[idx]);
				}
				
				#line 183 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				return def;
			}
			#line default
		}
		
		
		public virtual bool exists(int key) {
			unchecked {
				#line 187 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				int idx = -1;
				#line 189 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				bool tmp = default(bool);
				#line 189 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				if (( this.cachedKey == key )) {
					#line 189 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					idx = this.cachedIndex;
					#line 189 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					tmp = ( idx != -1 );
				}
				else {
					#line 189 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					tmp = false;
				}
				
				#line 189 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				if (tmp) {
					#line 190 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					return true;
				}
				
				#line 194 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				idx = this.lookup(key);
				if (( idx != -1 )) {
					#line 197 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					this.cachedKey = key;
					this.cachedIndex = idx;
					#line 201 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					return true;
				}
				
				#line 204 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				return false;
			}
			#line default
		}
		
		
		public virtual bool @remove(int key) {
			unchecked {
				#line 208 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				int idx = -1;
				#line 210 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				bool tmp = default(bool);
				#line 210 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				if (( this.cachedKey == key )) {
					#line 210 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					idx = this.cachedIndex;
					#line 210 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					tmp = ( idx != -1 );
				}
				else {
					#line 210 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					tmp = false;
				}
				
				#line 210 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				if ( ! (tmp) ) {
					#line 213 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					idx = this.lookup(key);
				}
				
				#line 216 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				if (( idx == -1 )) {
					#line 217 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					return false;
				}
				else {
					#line 220 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					if (( this.cachedKey == key )) {
						#line 221 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						this.cachedIndex = -1;
					}
					
					#line 224 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					if (( (( ((int) (( ((uint) (this.flags[( idx >> 4 )]) ) >> (( (( idx & 15 )) << 1 )) )) ) & 3 )) == 0 )) {
						#line 225 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						this.flags[( idx >> 4 )] |= ( 1 << (( (( idx & 15 )) << 1 )) );
						 -- this.size;
						#line 228 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						this.vals[idx] = default(T);
					}
					
					#line 236 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					return true;
				}
				
			}
			#line default
		}
		
		
		public void resize(int newNBuckets) {
			unchecked {
				#line 242 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				int[] newFlags = null;
				int j = 1;
				#line 244 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				{
					#line 245 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					int x = newNBuckets;
					#line 245 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					 -- x;
					#line 245 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					x |= ((int) (( ((uint) (x) ) >> 1 )) );
					#line 245 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					x |= ((int) (( ((uint) (x) ) >> 2 )) );
					#line 245 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					x |= ((int) (( ((uint) (x) ) >> 4 )) );
					#line 245 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					x |= ((int) (( ((uint) (x) ) >> 8 )) );
					#line 245 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					x |= ((int) (( ((uint) (x) ) >> 16 )) );
					#line 245 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					 ++ x;
					#line 245 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					newNBuckets = x;
					if (( newNBuckets < 4 )) {
						#line 247 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						newNBuckets = 4;
					}
					
					#line 248 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					if (( this.size >= ( ( newNBuckets * 0.7 ) + 0.5 ) )) {
						#line 250 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						j = 0;
					}
					else {
						#line 252 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						int nfSize = ( (( newNBuckets < 16 )) ? (1) : (( newNBuckets >> 4 )) );
						newFlags = new int[nfSize];
						#line 254 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						{
							#line 254 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
							int _g = 0;
							#line 254 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
							int _g1 = nfSize;
							#line 254 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
							while (( _g < _g1 )) {
								#line 254 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
								int i = _g++;
								newFlags[i] = -1431655766;
							}
							
						}
						
						#line 257 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						if (( this.nBuckets < newNBuckets )) {
							#line 259 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
							int[] k = new int[newNBuckets];
							if (( this._keys != null )) {
								#line 261 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
								global::System.Array.Copy(((global::System.Array) (this._keys) ), ((int) (0) ), ((global::System.Array) (k) ), ((int) (0) ), ((int) (this.nBuckets) ));
							}
							
							#line 263 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
							this._keys = k;
							#line 265 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
							T[] v = new T[newNBuckets];
							if (( this.vals != null )) {
								#line 267 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
								global::System.Array.Copy(((global::System.Array) (this.vals) ), ((int) (0) ), ((global::System.Array) (v) ), ((int) (0) ), ((int) (this.nBuckets) ));
							}
							
							#line 269 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
							this.vals = v;
						}
						
					}
					
				}
				
				#line 274 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				if (( j != 0 )) {
					#line 277 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					this.cachedKey = 0;
					this.cachedIndex = -1;
					#line 281 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					j = -1;
					int nBuckets = this.nBuckets;
					int[] _keys = this._keys;
					T[] vals = this.vals;
					int[] flags = this.flags;
					#line 284 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					int newMask = ( newNBuckets - 1 );
					while ((  ++ j < nBuckets )) {
						#line 286 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						if (( (( ((int) (( ((uint) (flags[( j >> 4 )]) ) >> (( (( j & 15 )) << 1 )) )) ) & 3 )) == 0 )) {
							#line 287 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
							int key = _keys[j];
							T val = global::haxe.lang.Runtime.genericCast<T>(vals[j]);
							#line 292 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
							vals[j] = default(T);
							flags[( j >> 4 )] |= ( 1 << (( (( j & 15 )) << 1 )) );
							#line 294 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
							while (true) {
								#line 296 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
								int k1 = key;
								int inc = ( (( ( ( k1 >> 3 ) ^ ( k1 << 3 ) ) | 1 )) & newMask );
								#line 298 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
								int i1 = ( k1 & newMask );
								while (( (( ( ((int) (( ((uint) (newFlags[( i1 >> 4 )]) ) >> (( (( i1 & 15 )) << 1 )) )) ) & 3 ) & 2 )) == 0 )) {
									#line 300 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
									i1 = ( ( i1 + inc ) & newMask );
								}
								
								#line 302 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
								newFlags[( i1 >> 4 )] &=  ~ ((( 2 << (( (( i1 & 15 )) << 1 )) ))) ;
								#line 304 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
								if (( ( i1 < nBuckets ) && ( (( ((int) (( ((uint) (flags[( i1 >> 4 )]) ) >> (( (( i1 & 15 )) << 1 )) )) ) & 3 )) == 0 ) )) {
									#line 306 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
									{
										#line 307 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
										int tmp = _keys[i1];
										_keys[i1] = key;
										#line 309 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
										key = tmp;
									}
									
									#line 310 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
									{
										#line 311 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
										T tmp1 = global::haxe.lang.Runtime.genericCast<T>(vals[i1]);
										vals[i1] = val;
										#line 313 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
										val = tmp1;
									}
									
									#line 316 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
									flags[( i1 >> 4 )] |= ( 1 << (( (( i1 & 15 )) << 1 )) );
								}
								else {
									#line 318 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
									_keys[i1] = key;
									vals[i1] = val;
									#line 320 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
									break;
								}
								
							}
							
						}
						
					}
					
					#line 326 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					if (( nBuckets > newNBuckets )) {
						#line 328 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						{
							#line 329 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
							int[] k2 = new int[newNBuckets];
							global::System.Array.Copy(((global::System.Array) (_keys) ), ((int) (0) ), ((global::System.Array) (k2) ), ((int) (0) ), ((int) (newNBuckets) ));
							#line 331 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
							this._keys = k2;
						}
						
						#line 332 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						{
							#line 333 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
							T[] v1 = new T[newNBuckets];
							global::System.Array.Copy(((global::System.Array) (vals) ), ((int) (0) ), ((global::System.Array) (v1) ), ((int) (0) ), ((int) (newNBuckets) ));
							#line 335 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
							this.vals = v1;
						}
						
					}
					
					#line 339 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					this.flags = newFlags;
					this.nBuckets = newNBuckets;
					#line 341 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					this.nOccupied = this.size;
					this.upperBound = ((int) (( ( newNBuckets * 0.7 ) + .5 )) );
				}
				
			}
			#line default
		}
		
		
		public object keys() {
			#line 347 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			return new global::haxe.ds._IntMap.IntMapKeyIterator<T>(((global::haxe.ds.IntMap<T>) (this) ));
		}
		#line default
		
		public object iterator() {
			#line 351 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			return new global::haxe.ds._IntMap.IntMapValueIterator<T>(((global::haxe.ds.IntMap<T>) (this) ));
		}
		#line default
		
		public object keyValueIterator() {
			#line 355 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			return new global::haxe.iterators.MapKeyValueIterator<int, T>(((global::haxe.IMap<int, T>) (this) ));
		}
		#line default
		
		public virtual global::haxe.ds.IntMap<T> copy() {
			#line 359 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			global::haxe.ds.IntMap<T> copied = new global::haxe.ds.IntMap<T>();
			{
				#line 360 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				object key = ((object) (new global::haxe.ds._IntMap.IntMapKeyIterator<T>(((global::haxe.ds.IntMap<T>) (this) ))) );
				#line 360 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				while (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(key, "hasNext", 407283053, null))) {
					#line 360 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					int key1 = ((int) (global::haxe.lang.Runtime.toInt(global::haxe.lang.Runtime.callField(key, "next", 1224901875, null))) );
					copied.@set(key1, (this.@get(key1)).@value);
				}
				
			}
			
			#line 362 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			return copied;
		}
		#line default
		
		public virtual string toString() {
			#line 366 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			global::System.Text.StringBuilder s_b = new global::System.Text.StringBuilder();
			s_b.Append(((string) ("{") ));
			#line 368 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			object it = ((object) (new global::haxe.ds._IntMap.IntMapKeyIterator<T>(((global::haxe.ds.IntMap<T>) (this) ))) );
			{
				#line 369 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				object i = it;
				#line 369 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				while (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(i, "hasNext", 407283053, null))) {
					#line 369 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					int i1 = ((int) (global::haxe.lang.Runtime.toInt(global::haxe.lang.Runtime.callField(i, "next", 1224901875, null))) );
					s_b.Append(((string) (global::Std.@string(i1)) ));
					#line 371 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					s_b.Append(((string) (" => ") ));
					s_b.Append(((string) (global::Std.@string(global::Std.@string((this.@get(i1)).toDynamic()))) ));
					#line 373 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					if (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(it, "hasNext", 407283053, null))) {
						#line 374 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						s_b.Append(((string) (", ") ));
					}
					
				}
				
			}
			
			#line 376 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			s_b.Append(((string) ("}") ));
			return s_b.ToString();
		}
		#line default
		
		public virtual void clear() {
			unchecked {
				#line 381 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				this.flags = null;
				this._keys = null;
				#line 383 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				this.vals = null;
				this.nBuckets = 0;
				#line 385 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				this.size = 0;
				this.nOccupied = 0;
				#line 387 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				this.upperBound = 0;
				#line 389 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				this.cachedKey = 0;
				this.cachedIndex = -1;
			}
			#line default
		}
		
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				switch (hash) {
					case 922671056:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						this.cachedIndex = ((int) (@value) );
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return @value;
					}
					
					
					case 1395555037:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						this.cachedKey = ((int) (@value) );
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return @value;
					}
					
					
					case 2022294396:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						this.upperBound = ((int) (@value) );
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return @value;
					}
					
					
					case 480756972:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						this.nOccupied = ((int) (@value) );
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return @value;
					}
					
					
					case 1280549057:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						this.size = ((int) (@value) );
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return @value;
					}
					
					
					case 1537812987:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						this.nBuckets = ((int) (@value) );
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return @value;
					}
					
					
					default:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				switch (hash) {
					case 922671056:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						this.cachedIndex = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return @value;
					}
					
					
					case 1395555037:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						this.cachedKey = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return @value;
					}
					
					
					case 2022294396:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						this.upperBound = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return @value;
					}
					
					
					case 480756972:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						this.nOccupied = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return @value;
					}
					
					
					case 1280549057:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						this.size = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return @value;
					}
					
					
					case 1537812987:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						this.nBuckets = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return @value;
					}
					
					
					case 1313416818:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						this.vals = ((T[]) (@value) );
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return @value;
					}
					
					
					case 2048392659:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						this._keys = ((int[]) (@value) );
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return @value;
					}
					
					
					case 42740551:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						this.flags = ((int[]) (@value) );
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return @value;
					}
					
					
					default:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				switch (hash) {
					case 1213952397:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "clear", 1213952397)) );
					}
					
					
					case 946786476:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "toString", 946786476)) );
					}
					
					
					case 1103412149:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "copy", 1103412149)) );
					}
					
					
					case 1257164128:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "keyValueIterator", 1257164128)) );
					}
					
					
					case 328878574:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "iterator", 328878574)) );
					}
					
					
					case 1191633396:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "keys", 1191633396)) );
					}
					
					
					case 142301684:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "resize", 142301684)) );
					}
					
					
					case 76061764:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "remove", 76061764)) );
					}
					
					
					case 1071652316:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "exists", 1071652316)) );
					}
					
					
					case 1797611211:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "getDefault", 1797611211)) );
					}
					
					
					case 5144726:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get", 5144726)) );
					}
					
					
					case 1639293562:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "lookup", 1639293562)) );
					}
					
					
					case 5741474:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "set", 5741474)) );
					}
					
					
					case 922671056:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return this.cachedIndex;
					}
					
					
					case 1395555037:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return this.cachedKey;
					}
					
					
					case 2022294396:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return this.upperBound;
					}
					
					
					case 480756972:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return this.nOccupied;
					}
					
					
					case 1280549057:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return this.size;
					}
					
					
					case 1537812987:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return this.nBuckets;
					}
					
					
					case 1313416818:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return this.vals;
					}
					
					
					case 2048392659:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return this._keys;
					}
					
					
					case 42740551:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return this.flags;
					}
					
					
					default:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				switch (hash) {
					case 922671056:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return ((double) (this.cachedIndex) );
					}
					
					
					case 1395555037:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return ((double) (this.cachedKey) );
					}
					
					
					case 2022294396:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return ((double) (this.upperBound) );
					}
					
					
					case 480756972:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return ((double) (this.nOccupied) );
					}
					
					
					case 1280549057:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return ((double) (this.size) );
					}
					
					
					case 1537812987:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return ((double) (this.nBuckets) );
					}
					
					
					default:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				switch (hash) {
					case 1213952397:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						this.clear();
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						break;
					}
					
					
					case 946786476:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return this.toString();
					}
					
					
					case 1103412149:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return this.copy();
					}
					
					
					case 1257164128:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return this.keyValueIterator();
					}
					
					
					case 328878574:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return this.iterator();
					}
					
					
					case 1191633396:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return this.keys();
					}
					
					
					case 142301684:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						this.resize(((int) (global::haxe.lang.Runtime.toInt(dynargs[0])) ));
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						break;
					}
					
					
					case 76061764:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return this.@remove(((int) (global::haxe.lang.Runtime.toInt(dynargs[0])) ));
					}
					
					
					case 1071652316:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return this.exists(((int) (global::haxe.lang.Runtime.toInt(dynargs[0])) ));
					}
					
					
					case 1797611211:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return this.getDefault(((int) (global::haxe.lang.Runtime.toInt(dynargs[0])) ), global::haxe.lang.Runtime.genericCast<T>(dynargs[1]));
					}
					
					
					case 5144726:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return (this.@get(((int) (global::haxe.lang.Runtime.toInt(dynargs[0])) ))).toDynamic();
					}
					
					
					case 1639293562:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return this.lookup(((int) (global::haxe.lang.Runtime.toInt(dynargs[0])) ));
					}
					
					
					case 5741474:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						this.@set(((int) (global::haxe.lang.Runtime.toInt(dynargs[0])) ), global::haxe.lang.Runtime.genericCast<T>(dynargs[1]));
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						break;
					}
					
					
					default:
					{
						#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				return null;
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			baseArr.push("cachedIndex");
			#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			baseArr.push("cachedKey");
			#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			baseArr.push("upperBound");
			#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			baseArr.push("nOccupied");
			#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			baseArr.push("size");
			#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			baseArr.push("nBuckets");
			#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			baseArr.push("vals");
			#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			baseArr.push("_keys");
			#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			baseArr.push("flags");
			#line 34 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
		public override string ToString(){
			return this.toString();
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.ds {
	[global::haxe.lang.GenericInterface(typeof(global::haxe.ds.IntMap<object>))]
	public interface IntMap : global::haxe.lang.IHxObject, global::haxe.lang.IGenericObject {
		
		object haxe_ds_IntMap_cast<T_c>();
		
		object haxe_IMap_cast<K_c, V_c>();
		
		int lookup(int key);
		
		bool exists(int key);
		
		bool @remove(int key);
		
		void resize(int newNBuckets);
		
		object keys();
		
		object iterator();
		
		object keyValueIterator();
		
		string toString();
		
		void clear();
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.ds._IntMap {
	public sealed class IntMapKeyIterator<T> : global::haxe.lang.HxObject, global::haxe.ds._IntMap.IntMapKeyIterator {
		
		public IntMapKeyIterator(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public IntMapKeyIterator(global::haxe.ds.IntMap<T> m) {
			#line 476 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			global::haxe.ds._IntMap.IntMapKeyIterator<object>.__hx_ctor_haxe_ds__IntMap_IntMapKeyIterator<T>(((global::haxe.ds._IntMap.IntMapKeyIterator<T>) (this) ), ((global::haxe.ds.IntMap<T>) (m) ));
		}
		#line default
		
		private static void __hx_ctor_haxe_ds__IntMap_IntMapKeyIterator<T_c>(global::haxe.ds._IntMap.IntMapKeyIterator<T_c> __hx_this, global::haxe.ds.IntMap<T_c> m) {
			#line 477 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			__hx_this.i = 0;
			__hx_this.m = m;
			#line 479 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			__hx_this.len = m.nBuckets;
		}
		#line default
		
		public static object __hx_cast<T_c_c>(global::haxe.ds._IntMap.IntMapKeyIterator me) {
			#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			return ( (( me != null )) ? (me.haxe_ds__IntMap_IntMapKeyIterator_cast<T_c_c>()) : default(object) );
		}
		#line default
		
		public object haxe_ds__IntMap_IntMapKeyIterator_cast<T_c>() {
			#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			if (global::haxe.lang.Runtime.eq(typeof(T), typeof(T_c))) {
				#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				return this;
			}
			
			#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			global::haxe.ds._IntMap.IntMapKeyIterator<T_c> new_me = new global::haxe.ds._IntMap.IntMapKeyIterator<T_c>(((global::haxe.lang.EmptyObject) (global::haxe.lang.EmptyObject.EMPTY) ));
			#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			global::Array<string> fields = global::Reflect.fields(this);
			#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			int i = 0;
			#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			while (( i < fields.length )) {
				#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				string field = fields[i++];
				#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				global::Reflect.setField(new_me, field, global::Reflect.field(this, field));
			}
			
			#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			return new_me;
		}
		#line default
		
		public global::haxe.ds.IntMap<T> m;
		
		public int i;
		
		public int len;
		
		public bool hasNext() {
			unchecked {
				#line 483 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				{
					#line 483 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					int _g = this.i;
					#line 483 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					int _g1 = this.len;
					#line 483 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					while (( _g < _g1 )) {
						#line 483 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						int j = _g++;
						if (( (( ((int) (( ((uint) (this.m.flags[( j >> 4 )]) ) >> (( (( j & 15 )) << 1 )) )) ) & 3 )) == 0 )) {
							#line 485 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
							this.i = j;
							return true;
						}
						
					}
					
				}
				
				#line 489 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				return false;
			}
			#line default
		}
		
		
		public int next() {
			#line 493 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			int ret = this.m._keys[this.i];
			#line 495 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			this.m.cachedIndex = this.i;
			this.m.cachedKey = ret;
			#line 498 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			this.i++;
			return ret;
		}
		#line default
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				switch (hash) {
					case 5393365:
					{
						#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						this.len = ((int) (@value) );
						#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return @value;
					}
					
					
					case 105:
					{
						#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						this.i = ((int) (@value) );
						#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return @value;
					}
					
					
					default:
					{
						#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				switch (hash) {
					case 5393365:
					{
						#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						this.len = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return @value;
					}
					
					
					case 105:
					{
						#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						this.i = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return @value;
					}
					
					
					case 109:
					{
						#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						this.m = ((global::haxe.ds.IntMap<T>) (global::haxe.ds.IntMap<object>.__hx_cast<T>(((global::haxe.ds.IntMap) (@value) ))) );
						#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return @value;
					}
					
					
					default:
					{
						#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				switch (hash) {
					case 1224901875:
					{
						#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "next", 1224901875)) );
					}
					
					
					case 407283053:
					{
						#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "hasNext", 407283053)) );
					}
					
					
					case 5393365:
					{
						#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return this.len;
					}
					
					
					case 105:
					{
						#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return this.i;
					}
					
					
					case 109:
					{
						#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return this.m;
					}
					
					
					default:
					{
						#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				switch (hash) {
					case 5393365:
					{
						#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return ((double) (this.len) );
					}
					
					
					case 105:
					{
						#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return ((double) (this.i) );
					}
					
					
					default:
					{
						#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				switch (hash) {
					case 1224901875:
					{
						#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return this.next();
					}
					
					
					case 407283053:
					{
						#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return this.hasNext();
					}
					
					
					default:
					{
						#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			baseArr.push("len");
			#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			baseArr.push("i");
			#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			baseArr.push("m");
			#line 471 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.ds._IntMap {
	[global::haxe.lang.GenericInterface(typeof(global::haxe.ds._IntMap.IntMapKeyIterator<object>))]
	public interface IntMapKeyIterator : global::haxe.lang.IHxObject, global::haxe.lang.IGenericObject {
		
		object haxe_ds__IntMap_IntMapKeyIterator_cast<T_c>();
		
		bool hasNext();
		
		int next();
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.ds._IntMap {
	public sealed class IntMapValueIterator<T> : global::haxe.lang.HxObject, global::haxe.ds._IntMap.IntMapValueIterator {
		
		public IntMapValueIterator(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public IntMapValueIterator(global::haxe.ds.IntMap<T> m) {
			#line 509 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			global::haxe.ds._IntMap.IntMapValueIterator<object>.__hx_ctor_haxe_ds__IntMap_IntMapValueIterator<T>(((global::haxe.ds._IntMap.IntMapValueIterator<T>) (this) ), ((global::haxe.ds.IntMap<T>) (m) ));
		}
		#line default
		
		private static void __hx_ctor_haxe_ds__IntMap_IntMapValueIterator<T_c>(global::haxe.ds._IntMap.IntMapValueIterator<T_c> __hx_this, global::haxe.ds.IntMap<T_c> m) {
			#line 510 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			__hx_this.i = 0;
			__hx_this.m = m;
			#line 512 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			__hx_this.len = m.nBuckets;
		}
		#line default
		
		public static object __hx_cast<T_c_c>(global::haxe.ds._IntMap.IntMapValueIterator me) {
			#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			return ( (( me != null )) ? (me.haxe_ds__IntMap_IntMapValueIterator_cast<T_c_c>()) : default(object) );
		}
		#line default
		
		public object haxe_ds__IntMap_IntMapValueIterator_cast<T_c>() {
			#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			if (global::haxe.lang.Runtime.eq(typeof(T), typeof(T_c))) {
				#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				return this;
			}
			
			#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			global::haxe.ds._IntMap.IntMapValueIterator<T_c> new_me = new global::haxe.ds._IntMap.IntMapValueIterator<T_c>(((global::haxe.lang.EmptyObject) (global::haxe.lang.EmptyObject.EMPTY) ));
			#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			global::Array<string> fields = global::Reflect.fields(this);
			#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			int i = 0;
			#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			while (( i < fields.length )) {
				#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				string field = fields[i++];
				#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				global::Reflect.setField(new_me, field, global::Reflect.field(this, field));
			}
			
			#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			return new_me;
		}
		#line default
		
		public global::haxe.ds.IntMap<T> m;
		
		public int i;
		
		public int len;
		
		public bool hasNext() {
			unchecked {
				#line 516 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				{
					#line 516 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					int _g = this.i;
					#line 516 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					int _g1 = this.len;
					#line 516 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
					while (( _g < _g1 )) {
						#line 516 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						int j = _g++;
						if (( (( ((int) (( ((uint) (this.m.flags[( j >> 4 )]) ) >> (( (( j & 15 )) << 1 )) )) ) & 3 )) == 0 )) {
							#line 518 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
							this.i = j;
							return true;
						}
						
					}
					
				}
				
				#line 522 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				return false;
			}
			#line default
		}
		
		
		public T next() {
			#line 526 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			return global::haxe.lang.Runtime.genericCast<T>(this.m.vals[this.i++]);
		}
		#line default
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				switch (hash) {
					case 5393365:
					{
						#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						this.len = ((int) (@value) );
						#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return @value;
					}
					
					
					case 105:
					{
						#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						this.i = ((int) (@value) );
						#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return @value;
					}
					
					
					default:
					{
						#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				switch (hash) {
					case 5393365:
					{
						#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						this.len = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return @value;
					}
					
					
					case 105:
					{
						#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						this.i = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return @value;
					}
					
					
					case 109:
					{
						#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						this.m = ((global::haxe.ds.IntMap<T>) (global::haxe.ds.IntMap<object>.__hx_cast<T>(((global::haxe.ds.IntMap) (@value) ))) );
						#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return @value;
					}
					
					
					default:
					{
						#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				switch (hash) {
					case 1224901875:
					{
						#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "next", 1224901875)) );
					}
					
					
					case 407283053:
					{
						#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "hasNext", 407283053)) );
					}
					
					
					case 5393365:
					{
						#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return this.len;
					}
					
					
					case 105:
					{
						#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return this.i;
					}
					
					
					case 109:
					{
						#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return this.m;
					}
					
					
					default:
					{
						#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				switch (hash) {
					case 5393365:
					{
						#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return ((double) (this.len) );
					}
					
					
					case 105:
					{
						#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return ((double) (this.i) );
					}
					
					
					default:
					{
						#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
				switch (hash) {
					case 1224901875:
					{
						#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return this.next();
					}
					
					
					case 407283053:
					{
						#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return this.hasNext();
					}
					
					
					default:
					{
						#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			baseArr.push("len");
			#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			baseArr.push("i");
			#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			baseArr.push("m");
			#line 504 "/opt/haxe/std/cs/_std/haxe/ds/IntMap.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.ds._IntMap {
	[global::haxe.lang.GenericInterface(typeof(global::haxe.ds._IntMap.IntMapValueIterator<object>))]
	public interface IntMapValueIterator : global::haxe.lang.IHxObject, global::haxe.lang.IGenericObject {
		
		object haxe_ds__IntMap_IntMapValueIterator_cast<T_c>();
		
		bool hasNext();
		
	}
}


