// Generated by Haxe 4.1.1

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe {
	public class Exception : global::System.Exception, global::haxe.lang.IHxObject {
		
		public Exception(global::haxe.lang.EmptyObject empty) : base(null, null) {
		}
		
		
		public Exception(string message, global::haxe.Exception previous, object native) : base(message, ( (( previous == null )) ? (null) : (previous) )) {
			unchecked {
				#line 16 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
				this.__skipStack = 0;
				#line 42 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
				{
					#line 44 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
					this.__previousException = previous;
					#line 46 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
					if (( ( native != null ) && ( native is global::System.Exception ) )) {
						#line 47 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						this.__nativeException = ((global::System.Exception) (((object) (native) )) );
						if (( this.__nativeException.StackTrace == null )) {
							#line 49 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
							this.__nativeStack = new global::System.Diagnostics.StackTrace(((int) (1) ), ((bool) (true) ));
							this.__ownStack = true;
						}
						else {
							#line 52 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
							this.__nativeStack = new global::System.Diagnostics.StackTrace(((global::System.Exception) (this.__nativeException) ), ((bool) (true) ));
							this.__ownStack = false;
						}
						
					}
					else {
						#line 56 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						this.__nativeException = ((global::System.Exception) (((object) (this) )) );
						this.__nativeStack = new global::System.Diagnostics.StackTrace(((int) (1) ), ((bool) (true) ));
						#line 58 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						this.__ownStack = true;
					}
					
				}
				
			}
			#line default
		}
		
		
		public static global::haxe.Exception caught(object @value) {
			#line 21 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
			if (global::Std.isOfType(((object) (@value) ), ((object) (typeof(global::haxe.Exception)) ))) {
				#line 22 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
				return ((global::haxe.Exception) (((object) (@value) )) );
			}
			else if (( @value is global::System.Exception )) {
				#line 24 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
				return new global::haxe.Exception(((global::System.Exception) (((object) (@value) )) ).Message, null, @value);
			}
			else {
				#line 26 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
				return new global::haxe.ValueException(@value, null, @value);
			}
			
		}
		#line default
		
		public static object thrown(object @value) {
			#line 31 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
			if (( @value is global::haxe.Exception )) {
				#line 32 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
				return ((global::haxe.Exception) (((object) (@value) )) ).get_native();
			}
			else if (( @value is global::System.Exception )) {
				#line 34 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
				return @value;
			}
			else {
				#line 36 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
				global::haxe.ValueException e = new global::haxe.ValueException(@value, null, null);
				if (e.__ownStack) {
					#line 37 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
					e.__skipStack++;
				}
				
				#line 38 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
				return ((object) (e) );
			}
			
		}
		#line default
		
		
		
		
		
		
		
		
		
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		public global::Array<object> __exceptionStack;
		
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		public global::System.Diagnostics.StackTrace __nativeStack;
		
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		public bool __ownStack;
		
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		public int __skipStack;
		
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		public global::System.Exception __nativeException;
		
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		public global::haxe.Exception __previousException;
		
		public virtual object unwrap() {
			#line 63 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
			return ((object) (this.__nativeException) );
		}
		#line default
		
		public virtual string toString() {
			#line 67 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
			return this.get_message();
		}
		#line default
		
		public virtual string details() {
			#line 71 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
			if (( this.get_previous() == null )) {
				#line 71 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
				string tmp = global::haxe.lang.Runtime.concat("Exception: ", this.get_message());
				#line 71 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
				global::Array<object> tmp1 = this.get_stack();
				#line 71 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
				return global::haxe.lang.Runtime.concat(tmp, (( (( tmp1 == null )) ? ("null") : (global::haxe._CallStack.CallStack_Impl_.toString(tmp1)) )));
			}
			else {
				#line 71 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
				string result = "";
				#line 71 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
				global::haxe.Exception e = this;
				#line 71 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
				global::haxe.Exception prev = null;
				#line 71 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
				while (( e != null )) {
					#line 71 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
					if (( prev == null )) {
						#line 71 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						string result1 = global::haxe.lang.Runtime.concat("Exception: ", e.get_message());
						#line 71 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						global::Array<object> tmp2 = e.get_stack();
						#line 71 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						result = global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat(result1, (( (( tmp2 == null )) ? ("null") : (global::haxe._CallStack.CallStack_Impl_.toString(tmp2)) ))), result);
					}
					else {
						#line 71 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						global::Array<object> prevStack = global::haxe._CallStack.CallStack_Impl_.subtract(e.get_stack(), prev.get_stack());
						#line 71 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						result = global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("Exception: ", e.get_message()), (( (( prevStack == null )) ? ("null") : (global::haxe._CallStack.CallStack_Impl_.toString(prevStack)) ))), "\n\nNext "), result);
					}
					
					#line 71 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
					prev = e;
					#line 71 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
					e = e.get_previous();
				}
				
				#line 71 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
				return result;
			}
			
		}
		#line default
		
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		public void __shiftStack() {
			#line 77 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
			if (this.__ownStack) {
				#line 77 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
				this.__skipStack++;
			}
			
		}
		#line default
		
		public virtual string get_message() {
			#line 81 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
			return this.Message;
		}
		#line default
		
		public virtual global::haxe.Exception get_previous() {
			#line 85 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
			return this.__previousException;
		}
		#line default
		
		public object get_native() {
			#line 89 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
			return ((object) (this.__nativeException) );
		}
		#line default
		
		public virtual global::Array<object> get_stack() {
			#line 93 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
			global::Array<object> _g = this.__exceptionStack;
			if (( _g == null )) {
				#line 95 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
				return this.__exceptionStack = global::haxe.NativeStackTrace.toHaxe(this.__nativeStack, new global::haxe.lang.Null<int>(this.__skipStack, true));
			}
			else {
				#line 96 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
				global::Array<object> s = _g;
				#line 96 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
				return s;
			}
			
		}
		#line default
		
		public virtual object __hx_lookupField(string field, int hash, bool throwErrors, bool isCheck) {
			#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
			if (isCheck) {
				#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
				return global::haxe.lang.Runtime.undefined;
			}
			else if (throwErrors) {
				#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
				throw new global::System.MemberAccessException("Field not found.");
			}
			else {
				#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
				return null;
			}
			
		}
		#line default
		
		public virtual double __hx_lookupField_f(string field, int hash, bool throwErrors) {
			#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
			if (throwErrors) {
				#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
				throw new global::System.MemberAccessException("Field not found or incompatible field type.");
			}
			else {
				#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
				return default(double);
			}
			
		}
		#line default
		
		public virtual object __hx_lookupSetField(string field, int hash, object @value) {
			#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
			throw new global::System.MemberAccessException("Cannot access field for writing.");
		}
		#line default
		
		public virtual double __hx_lookupSetField_f(string field, int hash, double @value) {
			#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
			throw new global::System.MemberAccessException("Cannot access field for writing or incompatible type.");
		}
		#line default
		
		public virtual double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
				switch (hash) {
					case 1177754921:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						this.__skipStack = ((int) (@value) );
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return @value;
					}
					
					
					default:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return this.__hx_lookupSetField_f(field, hash, @value);
					}
					
				}
				
			}
			#line default
		}
		
		
		public virtual object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
				switch (hash) {
					case 78945784:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						this.__previousException = ((global::haxe.Exception) (@value) );
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return @value;
					}
					
					
					case 221637784:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						this.__nativeException = ((global::System.Exception) (@value) );
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return @value;
					}
					
					
					case 1177754921:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						this.__skipStack = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return @value;
					}
					
					
					case 1460447810:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						this.__ownStack = global::haxe.lang.Runtime.toBool(@value);
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return @value;
					}
					
					
					case 863972113:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						this.__nativeStack = ((global::System.Diagnostics.StackTrace) (@value) );
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return @value;
					}
					
					
					case 1066783641:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						this.__exceptionStack = ((global::Array<object>) (global::Array<object>.__hx_cast<object>(((global::Array) (@value) ))) );
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return @value;
					}
					
					
					default:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return this.__hx_lookupSetField(field, hash, @value);
					}
					
				}
				
			}
			#line default
		}
		
		
		public virtual object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
				switch (hash) {
					case 1203028895:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get_stack", 1203028895)) );
					}
					
					
					case 312752480:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get_native", 312752480)) );
					}
					
					
					case 1489662016:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get_previous", 1489662016)) );
					}
					
					
					case 537630174:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get_message", 537630174)) );
					}
					
					
					case 1274465926:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "__shiftStack", 1274465926)) );
					}
					
					
					case 727112898:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "details", 727112898)) );
					}
					
					
					case 946786476:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "toString", 946786476)) );
					}
					
					
					case 1825849507:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "unwrap", 1825849507)) );
					}
					
					
					case 78945784:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return this.__previousException;
					}
					
					
					case 221637784:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return this.__nativeException;
					}
					
					
					case 1177754921:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return this.__skipStack;
					}
					
					
					case 1460447810:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return this.__ownStack;
					}
					
					
					case 863972113:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return this.__nativeStack;
					}
					
					
					case 1066783641:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return this.__exceptionStack;
					}
					
					
					case 572311959:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return this.get_native();
					}
					
					
					case 598785079:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return this.get_previous();
					}
					
					
					case 67856200:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return this.get_stack();
					}
					
					
					case 437335495:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return this.get_message();
					}
					
					
					default:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return this.__hx_lookupField(field, hash, throwErrors, isCheck);
					}
					
				}
				
			}
			#line default
		}
		
		
		public virtual double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
				switch (hash) {
					case 1177754921:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return ((double) (this.__skipStack) );
					}
					
					
					case 572311959:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return ((double) (global::haxe.lang.Runtime.toDouble(this.get_native())) );
					}
					
					
					default:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return this.__hx_lookupField_f(field, hash, throwErrors);
					}
					
				}
				
			}
			#line default
		}
		
		
		public virtual object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
				switch (hash) {
					case 1203028895:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return this.get_stack();
					}
					
					
					case 312752480:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return this.get_native();
					}
					
					
					case 1489662016:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return this.get_previous();
					}
					
					
					case 537630174:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return this.get_message();
					}
					
					
					case 1274465926:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						this.__shiftStack();
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						break;
					}
					
					
					case 727112898:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return this.details();
					}
					
					
					case 946786476:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return this.toString();
					}
					
					
					case 1825849507:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return this.unwrap();
					}
					
					
					default:
					{
						#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
						return ((global::haxe.lang.Function) (this.__hx_getField(field, hash, true, false, false)) ).__hx_invokeDynamic(dynargs);
					}
					
				}
				
				#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
				return null;
			}
			#line default
		}
		
		
		public virtual void __hx_getFields(global::Array<string> baseArr) {
			#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
			baseArr.push("__previousException");
			#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
			baseArr.push("__nativeException");
			#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
			baseArr.push("__skipStack");
			#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
			baseArr.push("__ownStack");
			#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
			baseArr.push("__nativeStack");
			#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
			baseArr.push("__exceptionStack");
			#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
			baseArr.push("native");
			#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
			baseArr.push("previous");
			#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
			baseArr.push("stack");
			#line 7 "/opt/haxe/std/cs/_std/haxe/Exception.hx"
			baseArr.push("message");
		}
		#line default
		
		public override string ToString(){
			return this.toString();
		}
		
		
	}
}


