// Generated by Haxe 4.1.1

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe {
	public class SysTools : global::haxe.lang.HxObject {
		
		static SysTools() {
			unchecked{
				#line 9 "/opt/haxe/std/haxe/SysTools.hx"
				global::haxe.SysTools.winMetaCharacters = ((global::Array<int>) (new global::Array<int>(new int[]{32, 40, 41, 37, 33, 94, 34, 60, 62, 38, 124, 10, 13, 44, 59})) );
			}
		}
		#line default
		
		public SysTools(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public SysTools() {
			#line 5 "/opt/haxe/std/haxe/SysTools.hx"
			global::haxe.SysTools.__hx_ctor_haxe_SysTools(this);
		}
		#line default
		
		protected static void __hx_ctor_haxe_SysTools(global::haxe.SysTools __hx_this) {
		}
		
		
		public static global::Array<int> winMetaCharacters;
		
		public static string quoteUnixArg(string argument) {
			#line 22 "/opt/haxe/std/haxe/SysTools.hx"
			if (( argument == "" )) {
				#line 23 "/opt/haxe/std/haxe/SysTools.hx"
				return "\'\'";
			}
			
			#line 25 "/opt/haxe/std/haxe/SysTools.hx"
			if ( ! (new global::EReg("[^a-zA-Z0-9_@%+=:,./-]", "").match(argument)) ) {
				#line 26 "/opt/haxe/std/haxe/SysTools.hx"
				return argument;
			}
			
			#line 30 "/opt/haxe/std/haxe/SysTools.hx"
			return global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("\'", global::StringTools.replace(argument, "\'", "\'\"\'\"\'")), "\'");
		}
		#line default
		
		public static string quoteWinArg(string argument, bool escapeMetaCharacters) {
			unchecked {
				#line 48 "/opt/haxe/std/haxe/SysTools.hx"
				if ( ! (new global::EReg("^[^ \t\\\\\"]+$", "").match(argument)) ) {
					#line 52 "/opt/haxe/std/haxe/SysTools.hx"
					global::StringBuf result = new global::StringBuf();
					bool needquote = ( ( ( global::haxe.lang.StringExt.indexOf(argument, " ", default(global::haxe.lang.Null<int>)) != -1 ) || ( global::haxe.lang.StringExt.indexOf(argument, "\t", default(global::haxe.lang.Null<int>)) != -1 ) ) || ( argument == "" ) );
					#line 55 "/opt/haxe/std/haxe/SysTools.hx"
					if (needquote) {
						#line 56 "/opt/haxe/std/haxe/SysTools.hx"
						result.b.Append(((string) ("\"") ));
					}
					
					#line 58 "/opt/haxe/std/haxe/SysTools.hx"
					global::StringBuf bs_buf = new global::StringBuf();
					{
						#line 59 "/opt/haxe/std/haxe/SysTools.hx"
						int _g = 0;
						#line 59 "/opt/haxe/std/haxe/SysTools.hx"
						int _g1 = argument.Length;
						#line 59 "/opt/haxe/std/haxe/SysTools.hx"
						while (( _g < _g1 )) {
							#line 59 "/opt/haxe/std/haxe/SysTools.hx"
							int i = _g++;
							{
								#line 60 "/opt/haxe/std/haxe/SysTools.hx"
								global::haxe.lang.Null<int> _g2 = global::haxe.lang.StringExt.charCodeAt(argument, i);
								#line 60 "/opt/haxe/std/haxe/SysTools.hx"
								if ( ! (_g2.hasValue) ) {
									#line 71 "/opt/haxe/std/haxe/SysTools.hx"
									global::haxe.lang.Null<int> c = _g2;
									#line 71 "/opt/haxe/std/haxe/SysTools.hx"
									{
										#line 73 "/opt/haxe/std/haxe/SysTools.hx"
										if (( bs_buf.b.Length > 0 )) {
											#line 74 "/opt/haxe/std/haxe/SysTools.hx"
											{
												#line 74 "/opt/haxe/std/haxe/SysTools.hx"
												string x = bs_buf.b.ToString();
												#line 74 "/opt/haxe/std/haxe/SysTools.hx"
												result.b.Append(((string) (global::Std.@string(x)) ));
											}
											
											#line 75 "/opt/haxe/std/haxe/SysTools.hx"
											bs_buf = new global::StringBuf();
										}
										
										#line 77 "/opt/haxe/std/haxe/SysTools.hx"
										result.addChar((c).@value);
									}
									
								}
								else {
									#line 60 "/opt/haxe/std/haxe/SysTools.hx"
									switch (((_g2)).@value) {
										case 34:
										{
											#line 66 "/opt/haxe/std/haxe/SysTools.hx"
											string bs = bs_buf.b.ToString();
											result.b.Append(((string) (global::Std.@string(bs)) ));
											#line 68 "/opt/haxe/std/haxe/SysTools.hx"
											result.b.Append(((string) (global::Std.@string(bs)) ));
											bs_buf = new global::StringBuf();
											#line 70 "/opt/haxe/std/haxe/SysTools.hx"
											result.b.Append(((string) ("\\\"") ));
											#line 64 "/opt/haxe/std/haxe/SysTools.hx"
											break;
										}
										
										
										case 92:
										{
											#line 63 "/opt/haxe/std/haxe/SysTools.hx"
											bs_buf.b.Append(((string) ("\\") ));
											#line 63 "/opt/haxe/std/haxe/SysTools.hx"
											break;
										}
										
										
										default:
										{
											#line 71 "/opt/haxe/std/haxe/SysTools.hx"
											global::haxe.lang.Null<int> c1 = _g2;
											#line 71 "/opt/haxe/std/haxe/SysTools.hx"
											{
												#line 73 "/opt/haxe/std/haxe/SysTools.hx"
												if (( bs_buf.b.Length > 0 )) {
													#line 74 "/opt/haxe/std/haxe/SysTools.hx"
													{
														#line 74 "/opt/haxe/std/haxe/SysTools.hx"
														string x1 = bs_buf.b.ToString();
														#line 74 "/opt/haxe/std/haxe/SysTools.hx"
														result.b.Append(((string) (global::Std.@string(x1)) ));
													}
													
													#line 75 "/opt/haxe/std/haxe/SysTools.hx"
													bs_buf = new global::StringBuf();
												}
												
												#line 77 "/opt/haxe/std/haxe/SysTools.hx"
												result.addChar((c1).@value);
											}
											
											#line 71 "/opt/haxe/std/haxe/SysTools.hx"
											break;
										}
										
									}
									
								}
								
							}
							
						}
						
					}
					
					#line 82 "/opt/haxe/std/haxe/SysTools.hx"
					{
						#line 82 "/opt/haxe/std/haxe/SysTools.hx"
						string x2 = bs_buf.b.ToString();
						#line 82 "/opt/haxe/std/haxe/SysTools.hx"
						result.b.Append(((string) (global::Std.@string(x2)) ));
					}
					
					#line 84 "/opt/haxe/std/haxe/SysTools.hx"
					if (needquote) {
						#line 85 "/opt/haxe/std/haxe/SysTools.hx"
						{
							#line 85 "/opt/haxe/std/haxe/SysTools.hx"
							string x3 = bs_buf.b.ToString();
							#line 85 "/opt/haxe/std/haxe/SysTools.hx"
							result.b.Append(((string) (global::Std.@string(x3)) ));
						}
						
						#line 86 "/opt/haxe/std/haxe/SysTools.hx"
						result.b.Append(((string) ("\"") ));
					}
					
					#line 89 "/opt/haxe/std/haxe/SysTools.hx"
					argument = result.b.ToString();
				}
				
				#line 92 "/opt/haxe/std/haxe/SysTools.hx"
				if (escapeMetaCharacters) {
					#line 93 "/opt/haxe/std/haxe/SysTools.hx"
					global::StringBuf result1 = new global::StringBuf();
					{
						#line 94 "/opt/haxe/std/haxe/SysTools.hx"
						int _g3 = 0;
						#line 94 "/opt/haxe/std/haxe/SysTools.hx"
						int _g4 = argument.Length;
						#line 94 "/opt/haxe/std/haxe/SysTools.hx"
						while (( _g3 < _g4 )) {
							#line 94 "/opt/haxe/std/haxe/SysTools.hx"
							int i1 = _g3++;
							global::haxe.lang.Null<int> c2 = global::haxe.lang.StringExt.charCodeAt(argument, i1);
							#line 96 "/opt/haxe/std/haxe/SysTools.hx"
							if (( global::haxe.SysTools.winMetaCharacters.indexOf((c2).@value, default(global::haxe.lang.Null<int>)) >= 0 )) {
								#line 97 "/opt/haxe/std/haxe/SysTools.hx"
								result1.addChar(94);
							}
							
							#line 99 "/opt/haxe/std/haxe/SysTools.hx"
							result1.addChar((c2).@value);
						}
						
					}
					
					#line 101 "/opt/haxe/std/haxe/SysTools.hx"
					return result1.b.ToString();
				}
				else {
					#line 103 "/opt/haxe/std/haxe/SysTools.hx"
					return argument;
				}
				
			}
			#line default
		}
		
		
	}
}


